syntax = "proto3";
option java_multiple_files =  true;
package org.ds.paxos;
option java_package = "org.ds.paxos";

service Raft {
  rpc SendTransaction(ClientMessage) returns (Empty);
  rpc AppendEntries(AppendEntriesArgument) returns (AppendEntriesResult);
  rpc RequestVote(RequestVoteArguments) returns (RequestVoteResult);
  rpc printLog(Empty) returns (Empty);
  rpc sendAckToClient(Ack) returns (Empty);
  rpc sendReadRequest(ReadRequest) returns (Balance);
}



message Empty{
  int32 data = 1;
}

message Balance {
  double balance = 1;
  string accName = 2;
  bool failure = 3;
}

enum ReadConcern {
  LINEARIZABLE = 0;
  LOCAL = 1;
  MAJORITY = 2;
}
message ReadRequest {
  ReadConcern readConcern = 1;
  TimeStampProto timeStamp = 2; // for causal consistency
  string accName = 3;
}


message AckMessage {
  Transaction t = 1;
  TimeStampProto timStamp = 2;
  int32 currentLeader = 3;
}

message Ack {
  // later on we can add more fields like timestamp for causal consistency
  repeated AckMessage ackMessage = 1;
}

message ClientMessage {
  Transaction t = 1;
  int32 writeConcern = 2;
  TimeStampProto timeStamp = 3;
}

message Transaction {
  string sender = 1;
  string receiver = 2;
  double amount = 3;
  string id = 4;
}
message LogEntryProto {
  int32 logIndex = 1;
  int32 term = 2;
  int32 writeConcern = 3;
  Transaction t = 4;
  TimeStampProto timeStamp = 5;
  repeated bool serversThatReplicatedThisEntry = 6;
}

message TimeStampProto {
  int64 p = 1;
  int64 l = 2;
}

message Log {
  repeated LogEntryProto log = 1;
}

message AppendEntriesArgument {
  int32 leadersTerm = 1;
  int32 prevLogIndex = 2;
  int32 leadersId = 3;
  int32 prevLogTerm = 4;
  Log entriesToAppend = 5;
  int32 leadersCommit = 6;
  int32 ackIndex = 7;
  TimeStampProto timeStamp = 8;

}

message RequestVoteArguments {
  int32 candidatesTerm = 1;
  int32 candidateId = 2;
  int32 lastLogIndex = 3;
  int32 lastLogTerm = 4;
}

message AppendEntriesResult {
  int32 currentTerm = 1;
  bool isSuccessFull = 2;
  int32 followerId = 3;
  TimeStampProto timeStamp = 4;
}
message RequestVoteResult {
  int32 currentTerm = 1;
  bool isVoteGranted = 2;
}





//TOKEN BUCKET PROTO FILES

service TokenBucket {
  rpc GetTokenStatus(TokenStatusRequest) returns (TokenStatusResponse);
  rpc UpdateTokenState(TokenUpdateRequest) returns (Empty);
  rpc ConsumeTokens(TokenConsumeRequest) returns (TokenConsumeResponse);
}

message TokenStatusRequest {
  // Empty for now
}

message TokenStatusResponse {
  double tokensAvailable = 1;
  int64 lastUpdatedTime = 2;
}

message TokenUpdateRequest {
  double tokensRemaining = 1;
  int64 lastUpdatedTime = 2;
}

message TokenConsumeRequest {
  double requiredTokens = 1;
}

message TokenConsumeResponse {
  bool granted = 1;
  double tokensRemaining = 2;
  int64 lastUpdatedTime = 3;
}


