# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import RLBudget_pb2 as RLBudget__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in RLBudget_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RLBudgetServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictBudget = channel.unary_unary(
                '/org.ds.rl.RLBudgetService/PredictBudget',
                request_serializer=RLBudget__pb2.BudgetRequest.SerializeToString,
                response_deserializer=RLBudget__pb2.BudgetResponse.FromString,
                _registered_method=True)
        self.RecordExperience = channel.unary_unary(
                '/org.ds.rl.RLBudgetService/RecordExperience',
                request_serializer=RLBudget__pb2.Experience.SerializeToString,
                response_deserializer=RLBudget__pb2.AckResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/org.ds.rl.RLBudgetService/HealthCheck',
                request_serializer=RLBudget__pb2.HealthRequest.SerializeToString,
                response_deserializer=RLBudget__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.GetModelStats = channel.unary_unary(
                '/org.ds.rl.RLBudgetService/GetModelStats',
                request_serializer=RLBudget__pb2.StatsRequest.SerializeToString,
                response_deserializer=RLBudget__pb2.StatsResponse.FromString,
                _registered_method=True)


class RLBudgetServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PredictBudget(self, request, context):
        """Get budget prediction from the model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordExperience(self, request, context):
        """Send training sample to the model (for online learning)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Check model health
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelStats(self, request, context):
        """Get model statistics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RLBudgetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictBudget': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictBudget,
                    request_deserializer=RLBudget__pb2.BudgetRequest.FromString,
                    response_serializer=RLBudget__pb2.BudgetResponse.SerializeToString,
            ),
            'RecordExperience': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordExperience,
                    request_deserializer=RLBudget__pb2.Experience.FromString,
                    response_serializer=RLBudget__pb2.AckResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=RLBudget__pb2.HealthRequest.FromString,
                    response_serializer=RLBudget__pb2.HealthResponse.SerializeToString,
            ),
            'GetModelStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelStats,
                    request_deserializer=RLBudget__pb2.StatsRequest.FromString,
                    response_serializer=RLBudget__pb2.StatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'org.ds.rl.RLBudgetService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('org.ds.rl.RLBudgetService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RLBudgetService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PredictBudget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.ds.rl.RLBudgetService/PredictBudget',
            RLBudget__pb2.BudgetRequest.SerializeToString,
            RLBudget__pb2.BudgetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordExperience(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.ds.rl.RLBudgetService/RecordExperience',
            RLBudget__pb2.Experience.SerializeToString,
            RLBudget__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.ds.rl.RLBudgetService/HealthCheck',
            RLBudget__pb2.HealthRequest.SerializeToString,
            RLBudget__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.ds.rl.RLBudgetService/GetModelStats',
            RLBudget__pb2.StatsRequest.SerializeToString,
            RLBudget__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
