syntax = "proto3";

package bankraft;

service BankService {
  rpc ProcessTransaction(TransactionRequest) returns (TransactionResponse);
  rpc GetBalance(BalanceRequest) returns (BalanceResponse); // Add this

}

service RaftService {
  rpc AppendEntries(AppendEntriesRequest) returns (AppendEntriesResponse);
  rpc RequestVote(RequestVoteRequest) returns (RequestVoteResponse);
}

message TransactionRequest {
  string request_id = 1;
  string from_account = 2;
  string to_account = 3;
  double amount = 4;
  TransactionType type = 5;
}

enum TransactionType {
  DEPOSIT = 0;
  WITHDRAW = 1;
  TRANSFER = 2;
}

message TransactionResponse {
  bool success = 1;
  string message = 2;
  string leader_hint = 3;
}

message LogEntry {
  uint64 term = 1;
  uint64 index = 2;
  TransactionRequest command = 3;
}

message AppendEntriesRequest {
  uint64 term = 1;
  string leader_id = 2;
  uint64 prev_log_index = 3;
  uint64 prev_log_term = 4;
  repeated LogEntry entries = 5;
  uint64 leader_commit = 6;
}

message AppendEntriesResponse {
  uint64 term = 1;
  bool success = 2;
}

message RequestVoteRequest {
  uint64 term = 1;
  string candidate_id = 2;
  uint64 last_log_index = 3;
  uint64 last_log_term = 4;
}

message RequestVoteResponse {
  uint64 term = 1;
  bool vote_granted = 2;
}

message BalanceRequest {
  string account = 1;
}

message BalanceResponse {
  double balance = 1;
}