// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/Raft.proto
// Protobuf Java Version: 4.29.3

package org.ds.paxos;

/**
 * Protobuf type {@code org.ds.paxos.Ack}
 */
public final class Ack extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:org.ds.paxos.Ack)
    AckOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Ack.class.getName());
  }
  // Use Ack.newBuilder() to construct.
  private Ack(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Ack() {
    ackMessage_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_Ack_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_Ack_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.ds.paxos.Ack.class, org.ds.paxos.Ack.Builder.class);
  }

  public static final int ACKMESSAGE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<org.ds.paxos.AckMessage> ackMessage_;
  /**
   * <pre>
   * later on we can add more fields like timestamp for causal consistency
   * </pre>
   *
   * <code>repeated .org.ds.paxos.AckMessage ackMessage = 1;</code>
   */
  @java.lang.Override
  public java.util.List<org.ds.paxos.AckMessage> getAckMessageList() {
    return ackMessage_;
  }
  /**
   * <pre>
   * later on we can add more fields like timestamp for causal consistency
   * </pre>
   *
   * <code>repeated .org.ds.paxos.AckMessage ackMessage = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.ds.paxos.AckMessageOrBuilder> 
      getAckMessageOrBuilderList() {
    return ackMessage_;
  }
  /**
   * <pre>
   * later on we can add more fields like timestamp for causal consistency
   * </pre>
   *
   * <code>repeated .org.ds.paxos.AckMessage ackMessage = 1;</code>
   */
  @java.lang.Override
  public int getAckMessageCount() {
    return ackMessage_.size();
  }
  /**
   * <pre>
   * later on we can add more fields like timestamp for causal consistency
   * </pre>
   *
   * <code>repeated .org.ds.paxos.AckMessage ackMessage = 1;</code>
   */
  @java.lang.Override
  public org.ds.paxos.AckMessage getAckMessage(int index) {
    return ackMessage_.get(index);
  }
  /**
   * <pre>
   * later on we can add more fields like timestamp for causal consistency
   * </pre>
   *
   * <code>repeated .org.ds.paxos.AckMessage ackMessage = 1;</code>
   */
  @java.lang.Override
  public org.ds.paxos.AckMessageOrBuilder getAckMessageOrBuilder(
      int index) {
    return ackMessage_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < ackMessage_.size(); i++) {
      output.writeMessage(1, ackMessage_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < ackMessage_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, ackMessage_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.ds.paxos.Ack)) {
      return super.equals(obj);
    }
    org.ds.paxos.Ack other = (org.ds.paxos.Ack) obj;

    if (!getAckMessageList()
        .equals(other.getAckMessageList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAckMessageCount() > 0) {
      hash = (37 * hash) + ACKMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getAckMessageList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.ds.paxos.Ack parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.Ack parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.Ack parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.Ack parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.Ack parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.Ack parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.Ack parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.ds.paxos.Ack parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.ds.paxos.Ack parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.ds.paxos.Ack parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.ds.paxos.Ack parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.ds.paxos.Ack parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.ds.paxos.Ack prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.ds.paxos.Ack}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.ds.paxos.Ack)
      org.ds.paxos.AckOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_Ack_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_Ack_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.ds.paxos.Ack.class, org.ds.paxos.Ack.Builder.class);
    }

    // Construct using org.ds.paxos.Ack.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (ackMessageBuilder_ == null) {
        ackMessage_ = java.util.Collections.emptyList();
      } else {
        ackMessage_ = null;
        ackMessageBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_Ack_descriptor;
    }

    @java.lang.Override
    public org.ds.paxos.Ack getDefaultInstanceForType() {
      return org.ds.paxos.Ack.getDefaultInstance();
    }

    @java.lang.Override
    public org.ds.paxos.Ack build() {
      org.ds.paxos.Ack result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.ds.paxos.Ack buildPartial() {
      org.ds.paxos.Ack result = new org.ds.paxos.Ack(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.ds.paxos.Ack result) {
      if (ackMessageBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          ackMessage_ = java.util.Collections.unmodifiableList(ackMessage_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.ackMessage_ = ackMessage_;
      } else {
        result.ackMessage_ = ackMessageBuilder_.build();
      }
    }

    private void buildPartial0(org.ds.paxos.Ack result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.ds.paxos.Ack) {
        return mergeFrom((org.ds.paxos.Ack)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.ds.paxos.Ack other) {
      if (other == org.ds.paxos.Ack.getDefaultInstance()) return this;
      if (ackMessageBuilder_ == null) {
        if (!other.ackMessage_.isEmpty()) {
          if (ackMessage_.isEmpty()) {
            ackMessage_ = other.ackMessage_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAckMessageIsMutable();
            ackMessage_.addAll(other.ackMessage_);
          }
          onChanged();
        }
      } else {
        if (!other.ackMessage_.isEmpty()) {
          if (ackMessageBuilder_.isEmpty()) {
            ackMessageBuilder_.dispose();
            ackMessageBuilder_ = null;
            ackMessage_ = other.ackMessage_;
            bitField0_ = (bitField0_ & ~0x00000001);
            ackMessageBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getAckMessageFieldBuilder() : null;
          } else {
            ackMessageBuilder_.addAllMessages(other.ackMessage_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.ds.paxos.AckMessage m =
                  input.readMessage(
                      org.ds.paxos.AckMessage.parser(),
                      extensionRegistry);
              if (ackMessageBuilder_ == null) {
                ensureAckMessageIsMutable();
                ackMessage_.add(m);
              } else {
                ackMessageBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<org.ds.paxos.AckMessage> ackMessage_ =
      java.util.Collections.emptyList();
    private void ensureAckMessageIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        ackMessage_ = new java.util.ArrayList<org.ds.paxos.AckMessage>(ackMessage_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        org.ds.paxos.AckMessage, org.ds.paxos.AckMessage.Builder, org.ds.paxos.AckMessageOrBuilder> ackMessageBuilder_;

    /**
     * <pre>
     * later on we can add more fields like timestamp for causal consistency
     * </pre>
     *
     * <code>repeated .org.ds.paxos.AckMessage ackMessage = 1;</code>
     */
    public java.util.List<org.ds.paxos.AckMessage> getAckMessageList() {
      if (ackMessageBuilder_ == null) {
        return java.util.Collections.unmodifiableList(ackMessage_);
      } else {
        return ackMessageBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * later on we can add more fields like timestamp for causal consistency
     * </pre>
     *
     * <code>repeated .org.ds.paxos.AckMessage ackMessage = 1;</code>
     */
    public int getAckMessageCount() {
      if (ackMessageBuilder_ == null) {
        return ackMessage_.size();
      } else {
        return ackMessageBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * later on we can add more fields like timestamp for causal consistency
     * </pre>
     *
     * <code>repeated .org.ds.paxos.AckMessage ackMessage = 1;</code>
     */
    public org.ds.paxos.AckMessage getAckMessage(int index) {
      if (ackMessageBuilder_ == null) {
        return ackMessage_.get(index);
      } else {
        return ackMessageBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * later on we can add more fields like timestamp for causal consistency
     * </pre>
     *
     * <code>repeated .org.ds.paxos.AckMessage ackMessage = 1;</code>
     */
    public Builder setAckMessage(
        int index, org.ds.paxos.AckMessage value) {
      if (ackMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAckMessageIsMutable();
        ackMessage_.set(index, value);
        onChanged();
      } else {
        ackMessageBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * later on we can add more fields like timestamp for causal consistency
     * </pre>
     *
     * <code>repeated .org.ds.paxos.AckMessage ackMessage = 1;</code>
     */
    public Builder setAckMessage(
        int index, org.ds.paxos.AckMessage.Builder builderForValue) {
      if (ackMessageBuilder_ == null) {
        ensureAckMessageIsMutable();
        ackMessage_.set(index, builderForValue.build());
        onChanged();
      } else {
        ackMessageBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * later on we can add more fields like timestamp for causal consistency
     * </pre>
     *
     * <code>repeated .org.ds.paxos.AckMessage ackMessage = 1;</code>
     */
    public Builder addAckMessage(org.ds.paxos.AckMessage value) {
      if (ackMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAckMessageIsMutable();
        ackMessage_.add(value);
        onChanged();
      } else {
        ackMessageBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * later on we can add more fields like timestamp for causal consistency
     * </pre>
     *
     * <code>repeated .org.ds.paxos.AckMessage ackMessage = 1;</code>
     */
    public Builder addAckMessage(
        int index, org.ds.paxos.AckMessage value) {
      if (ackMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAckMessageIsMutable();
        ackMessage_.add(index, value);
        onChanged();
      } else {
        ackMessageBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * later on we can add more fields like timestamp for causal consistency
     * </pre>
     *
     * <code>repeated .org.ds.paxos.AckMessage ackMessage = 1;</code>
     */
    public Builder addAckMessage(
        org.ds.paxos.AckMessage.Builder builderForValue) {
      if (ackMessageBuilder_ == null) {
        ensureAckMessageIsMutable();
        ackMessage_.add(builderForValue.build());
        onChanged();
      } else {
        ackMessageBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * later on we can add more fields like timestamp for causal consistency
     * </pre>
     *
     * <code>repeated .org.ds.paxos.AckMessage ackMessage = 1;</code>
     */
    public Builder addAckMessage(
        int index, org.ds.paxos.AckMessage.Builder builderForValue) {
      if (ackMessageBuilder_ == null) {
        ensureAckMessageIsMutable();
        ackMessage_.add(index, builderForValue.build());
        onChanged();
      } else {
        ackMessageBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * later on we can add more fields like timestamp for causal consistency
     * </pre>
     *
     * <code>repeated .org.ds.paxos.AckMessage ackMessage = 1;</code>
     */
    public Builder addAllAckMessage(
        java.lang.Iterable<? extends org.ds.paxos.AckMessage> values) {
      if (ackMessageBuilder_ == null) {
        ensureAckMessageIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ackMessage_);
        onChanged();
      } else {
        ackMessageBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * later on we can add more fields like timestamp for causal consistency
     * </pre>
     *
     * <code>repeated .org.ds.paxos.AckMessage ackMessage = 1;</code>
     */
    public Builder clearAckMessage() {
      if (ackMessageBuilder_ == null) {
        ackMessage_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        ackMessageBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * later on we can add more fields like timestamp for causal consistency
     * </pre>
     *
     * <code>repeated .org.ds.paxos.AckMessage ackMessage = 1;</code>
     */
    public Builder removeAckMessage(int index) {
      if (ackMessageBuilder_ == null) {
        ensureAckMessageIsMutable();
        ackMessage_.remove(index);
        onChanged();
      } else {
        ackMessageBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * later on we can add more fields like timestamp for causal consistency
     * </pre>
     *
     * <code>repeated .org.ds.paxos.AckMessage ackMessage = 1;</code>
     */
    public org.ds.paxos.AckMessage.Builder getAckMessageBuilder(
        int index) {
      return getAckMessageFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * later on we can add more fields like timestamp for causal consistency
     * </pre>
     *
     * <code>repeated .org.ds.paxos.AckMessage ackMessage = 1;</code>
     */
    public org.ds.paxos.AckMessageOrBuilder getAckMessageOrBuilder(
        int index) {
      if (ackMessageBuilder_ == null) {
        return ackMessage_.get(index);  } else {
        return ackMessageBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * later on we can add more fields like timestamp for causal consistency
     * </pre>
     *
     * <code>repeated .org.ds.paxos.AckMessage ackMessage = 1;</code>
     */
    public java.util.List<? extends org.ds.paxos.AckMessageOrBuilder> 
         getAckMessageOrBuilderList() {
      if (ackMessageBuilder_ != null) {
        return ackMessageBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(ackMessage_);
      }
    }
    /**
     * <pre>
     * later on we can add more fields like timestamp for causal consistency
     * </pre>
     *
     * <code>repeated .org.ds.paxos.AckMessage ackMessage = 1;</code>
     */
    public org.ds.paxos.AckMessage.Builder addAckMessageBuilder() {
      return getAckMessageFieldBuilder().addBuilder(
          org.ds.paxos.AckMessage.getDefaultInstance());
    }
    /**
     * <pre>
     * later on we can add more fields like timestamp for causal consistency
     * </pre>
     *
     * <code>repeated .org.ds.paxos.AckMessage ackMessage = 1;</code>
     */
    public org.ds.paxos.AckMessage.Builder addAckMessageBuilder(
        int index) {
      return getAckMessageFieldBuilder().addBuilder(
          index, org.ds.paxos.AckMessage.getDefaultInstance());
    }
    /**
     * <pre>
     * later on we can add more fields like timestamp for causal consistency
     * </pre>
     *
     * <code>repeated .org.ds.paxos.AckMessage ackMessage = 1;</code>
     */
    public java.util.List<org.ds.paxos.AckMessage.Builder> 
         getAckMessageBuilderList() {
      return getAckMessageFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        org.ds.paxos.AckMessage, org.ds.paxos.AckMessage.Builder, org.ds.paxos.AckMessageOrBuilder> 
        getAckMessageFieldBuilder() {
      if (ackMessageBuilder_ == null) {
        ackMessageBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            org.ds.paxos.AckMessage, org.ds.paxos.AckMessage.Builder, org.ds.paxos.AckMessageOrBuilder>(
                ackMessage_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        ackMessage_ = null;
      }
      return ackMessageBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:org.ds.paxos.Ack)
  }

  // @@protoc_insertion_point(class_scope:org.ds.paxos.Ack)
  private static final org.ds.paxos.Ack DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.ds.paxos.Ack();
  }

  public static org.ds.paxos.Ack getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Ack>
      PARSER = new com.google.protobuf.AbstractParser<Ack>() {
    @java.lang.Override
    public Ack parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Ack> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Ack> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.ds.paxos.Ack getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

