// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/Raft.proto
// Protobuf Java Version: 4.29.3

package org.ds.paxos;

/**
 * Protobuf type {@code org.ds.paxos.AckMessage}
 */
public final class AckMessage extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:org.ds.paxos.AckMessage)
    AckMessageOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      AckMessage.class.getName());
  }
  // Use AckMessage.newBuilder() to construct.
  private AckMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AckMessage() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_AckMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_AckMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.ds.paxos.AckMessage.class, org.ds.paxos.AckMessage.Builder.class);
  }

  private int bitField0_;
  public static final int T_FIELD_NUMBER = 1;
  private org.ds.paxos.Transaction t_;
  /**
   * <code>.org.ds.paxos.Transaction t = 1;</code>
   * @return Whether the t field is set.
   */
  @java.lang.Override
  public boolean hasT() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.org.ds.paxos.Transaction t = 1;</code>
   * @return The t.
   */
  @java.lang.Override
  public org.ds.paxos.Transaction getT() {
    return t_ == null ? org.ds.paxos.Transaction.getDefaultInstance() : t_;
  }
  /**
   * <code>.org.ds.paxos.Transaction t = 1;</code>
   */
  @java.lang.Override
  public org.ds.paxos.TransactionOrBuilder getTOrBuilder() {
    return t_ == null ? org.ds.paxos.Transaction.getDefaultInstance() : t_;
  }

  public static final int TIMSTAMP_FIELD_NUMBER = 2;
  private org.ds.paxos.TimeStampProto timStamp_;
  /**
   * <code>.org.ds.paxos.TimeStampProto timStamp = 2;</code>
   * @return Whether the timStamp field is set.
   */
  @java.lang.Override
  public boolean hasTimStamp() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.org.ds.paxos.TimeStampProto timStamp = 2;</code>
   * @return The timStamp.
   */
  @java.lang.Override
  public org.ds.paxos.TimeStampProto getTimStamp() {
    return timStamp_ == null ? org.ds.paxos.TimeStampProto.getDefaultInstance() : timStamp_;
  }
  /**
   * <code>.org.ds.paxos.TimeStampProto timStamp = 2;</code>
   */
  @java.lang.Override
  public org.ds.paxos.TimeStampProtoOrBuilder getTimStampOrBuilder() {
    return timStamp_ == null ? org.ds.paxos.TimeStampProto.getDefaultInstance() : timStamp_;
  }

  public static final int CURRENTLEADER_FIELD_NUMBER = 3;
  private int currentLeader_ = 0;
  /**
   * <code>int32 currentLeader = 3;</code>
   * @return The currentLeader.
   */
  @java.lang.Override
  public int getCurrentLeader() {
    return currentLeader_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getT());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getTimStamp());
    }
    if (currentLeader_ != 0) {
      output.writeInt32(3, currentLeader_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getT());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getTimStamp());
    }
    if (currentLeader_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, currentLeader_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.ds.paxos.AckMessage)) {
      return super.equals(obj);
    }
    org.ds.paxos.AckMessage other = (org.ds.paxos.AckMessage) obj;

    if (hasT() != other.hasT()) return false;
    if (hasT()) {
      if (!getT()
          .equals(other.getT())) return false;
    }
    if (hasTimStamp() != other.hasTimStamp()) return false;
    if (hasTimStamp()) {
      if (!getTimStamp()
          .equals(other.getTimStamp())) return false;
    }
    if (getCurrentLeader()
        != other.getCurrentLeader()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasT()) {
      hash = (37 * hash) + T_FIELD_NUMBER;
      hash = (53 * hash) + getT().hashCode();
    }
    if (hasTimStamp()) {
      hash = (37 * hash) + TIMSTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimStamp().hashCode();
    }
    hash = (37 * hash) + CURRENTLEADER_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentLeader();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.ds.paxos.AckMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.AckMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.AckMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.AckMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.AckMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.AckMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.AckMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.ds.paxos.AckMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.ds.paxos.AckMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.ds.paxos.AckMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.ds.paxos.AckMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.ds.paxos.AckMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.ds.paxos.AckMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.ds.paxos.AckMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.ds.paxos.AckMessage)
      org.ds.paxos.AckMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_AckMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_AckMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.ds.paxos.AckMessage.class, org.ds.paxos.AckMessage.Builder.class);
    }

    // Construct using org.ds.paxos.AckMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getTFieldBuilder();
        getTimStampFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      t_ = null;
      if (tBuilder_ != null) {
        tBuilder_.dispose();
        tBuilder_ = null;
      }
      timStamp_ = null;
      if (timStampBuilder_ != null) {
        timStampBuilder_.dispose();
        timStampBuilder_ = null;
      }
      currentLeader_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_AckMessage_descriptor;
    }

    @java.lang.Override
    public org.ds.paxos.AckMessage getDefaultInstanceForType() {
      return org.ds.paxos.AckMessage.getDefaultInstance();
    }

    @java.lang.Override
    public org.ds.paxos.AckMessage build() {
      org.ds.paxos.AckMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.ds.paxos.AckMessage buildPartial() {
      org.ds.paxos.AckMessage result = new org.ds.paxos.AckMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.ds.paxos.AckMessage result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.t_ = tBuilder_ == null
            ? t_
            : tBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.timStamp_ = timStampBuilder_ == null
            ? timStamp_
            : timStampBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.currentLeader_ = currentLeader_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.ds.paxos.AckMessage) {
        return mergeFrom((org.ds.paxos.AckMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.ds.paxos.AckMessage other) {
      if (other == org.ds.paxos.AckMessage.getDefaultInstance()) return this;
      if (other.hasT()) {
        mergeT(other.getT());
      }
      if (other.hasTimStamp()) {
        mergeTimStamp(other.getTimStamp());
      }
      if (other.getCurrentLeader() != 0) {
        setCurrentLeader(other.getCurrentLeader());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getTFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getTimStampFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              currentLeader_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private org.ds.paxos.Transaction t_;
    private com.google.protobuf.SingleFieldBuilder<
        org.ds.paxos.Transaction, org.ds.paxos.Transaction.Builder, org.ds.paxos.TransactionOrBuilder> tBuilder_;
    /**
     * <code>.org.ds.paxos.Transaction t = 1;</code>
     * @return Whether the t field is set.
     */
    public boolean hasT() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.org.ds.paxos.Transaction t = 1;</code>
     * @return The t.
     */
    public org.ds.paxos.Transaction getT() {
      if (tBuilder_ == null) {
        return t_ == null ? org.ds.paxos.Transaction.getDefaultInstance() : t_;
      } else {
        return tBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.ds.paxos.Transaction t = 1;</code>
     */
    public Builder setT(org.ds.paxos.Transaction value) {
      if (tBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        t_ = value;
      } else {
        tBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.org.ds.paxos.Transaction t = 1;</code>
     */
    public Builder setT(
        org.ds.paxos.Transaction.Builder builderForValue) {
      if (tBuilder_ == null) {
        t_ = builderForValue.build();
      } else {
        tBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.org.ds.paxos.Transaction t = 1;</code>
     */
    public Builder mergeT(org.ds.paxos.Transaction value) {
      if (tBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          t_ != null &&
          t_ != org.ds.paxos.Transaction.getDefaultInstance()) {
          getTBuilder().mergeFrom(value);
        } else {
          t_ = value;
        }
      } else {
        tBuilder_.mergeFrom(value);
      }
      if (t_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.org.ds.paxos.Transaction t = 1;</code>
     */
    public Builder clearT() {
      bitField0_ = (bitField0_ & ~0x00000001);
      t_ = null;
      if (tBuilder_ != null) {
        tBuilder_.dispose();
        tBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.org.ds.paxos.Transaction t = 1;</code>
     */
    public org.ds.paxos.Transaction.Builder getTBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getTFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.ds.paxos.Transaction t = 1;</code>
     */
    public org.ds.paxos.TransactionOrBuilder getTOrBuilder() {
      if (tBuilder_ != null) {
        return tBuilder_.getMessageOrBuilder();
      } else {
        return t_ == null ?
            org.ds.paxos.Transaction.getDefaultInstance() : t_;
      }
    }
    /**
     * <code>.org.ds.paxos.Transaction t = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.ds.paxos.Transaction, org.ds.paxos.Transaction.Builder, org.ds.paxos.TransactionOrBuilder> 
        getTFieldBuilder() {
      if (tBuilder_ == null) {
        tBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.ds.paxos.Transaction, org.ds.paxos.Transaction.Builder, org.ds.paxos.TransactionOrBuilder>(
                getT(),
                getParentForChildren(),
                isClean());
        t_ = null;
      }
      return tBuilder_;
    }

    private org.ds.paxos.TimeStampProto timStamp_;
    private com.google.protobuf.SingleFieldBuilder<
        org.ds.paxos.TimeStampProto, org.ds.paxos.TimeStampProto.Builder, org.ds.paxos.TimeStampProtoOrBuilder> timStampBuilder_;
    /**
     * <code>.org.ds.paxos.TimeStampProto timStamp = 2;</code>
     * @return Whether the timStamp field is set.
     */
    public boolean hasTimStamp() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timStamp = 2;</code>
     * @return The timStamp.
     */
    public org.ds.paxos.TimeStampProto getTimStamp() {
      if (timStampBuilder_ == null) {
        return timStamp_ == null ? org.ds.paxos.TimeStampProto.getDefaultInstance() : timStamp_;
      } else {
        return timStampBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timStamp = 2;</code>
     */
    public Builder setTimStamp(org.ds.paxos.TimeStampProto value) {
      if (timStampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timStamp_ = value;
      } else {
        timStampBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timStamp = 2;</code>
     */
    public Builder setTimStamp(
        org.ds.paxos.TimeStampProto.Builder builderForValue) {
      if (timStampBuilder_ == null) {
        timStamp_ = builderForValue.build();
      } else {
        timStampBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timStamp = 2;</code>
     */
    public Builder mergeTimStamp(org.ds.paxos.TimeStampProto value) {
      if (timStampBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          timStamp_ != null &&
          timStamp_ != org.ds.paxos.TimeStampProto.getDefaultInstance()) {
          getTimStampBuilder().mergeFrom(value);
        } else {
          timStamp_ = value;
        }
      } else {
        timStampBuilder_.mergeFrom(value);
      }
      if (timStamp_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timStamp = 2;</code>
     */
    public Builder clearTimStamp() {
      bitField0_ = (bitField0_ & ~0x00000002);
      timStamp_ = null;
      if (timStampBuilder_ != null) {
        timStampBuilder_.dispose();
        timStampBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timStamp = 2;</code>
     */
    public org.ds.paxos.TimeStampProto.Builder getTimStampBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getTimStampFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timStamp = 2;</code>
     */
    public org.ds.paxos.TimeStampProtoOrBuilder getTimStampOrBuilder() {
      if (timStampBuilder_ != null) {
        return timStampBuilder_.getMessageOrBuilder();
      } else {
        return timStamp_ == null ?
            org.ds.paxos.TimeStampProto.getDefaultInstance() : timStamp_;
      }
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timStamp = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.ds.paxos.TimeStampProto, org.ds.paxos.TimeStampProto.Builder, org.ds.paxos.TimeStampProtoOrBuilder> 
        getTimStampFieldBuilder() {
      if (timStampBuilder_ == null) {
        timStampBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.ds.paxos.TimeStampProto, org.ds.paxos.TimeStampProto.Builder, org.ds.paxos.TimeStampProtoOrBuilder>(
                getTimStamp(),
                getParentForChildren(),
                isClean());
        timStamp_ = null;
      }
      return timStampBuilder_;
    }

    private int currentLeader_ ;
    /**
     * <code>int32 currentLeader = 3;</code>
     * @return The currentLeader.
     */
    @java.lang.Override
    public int getCurrentLeader() {
      return currentLeader_;
    }
    /**
     * <code>int32 currentLeader = 3;</code>
     * @param value The currentLeader to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentLeader(int value) {

      currentLeader_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 currentLeader = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentLeader() {
      bitField0_ = (bitField0_ & ~0x00000004);
      currentLeader_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:org.ds.paxos.AckMessage)
  }

  // @@protoc_insertion_point(class_scope:org.ds.paxos.AckMessage)
  private static final org.ds.paxos.AckMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.ds.paxos.AckMessage();
  }

  public static org.ds.paxos.AckMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AckMessage>
      PARSER = new com.google.protobuf.AbstractParser<AckMessage>() {
    @java.lang.Override
    public AckMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AckMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AckMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.ds.paxos.AckMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

