// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/Raft.proto
// Protobuf Java Version: 4.29.3

package org.ds.paxos;

public interface AckMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.ds.paxos.AckMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.ds.paxos.Transaction t = 1;</code>
   * @return Whether the t field is set.
   */
  boolean hasT();
  /**
   * <code>.org.ds.paxos.Transaction t = 1;</code>
   * @return The t.
   */
  org.ds.paxos.Transaction getT();
  /**
   * <code>.org.ds.paxos.Transaction t = 1;</code>
   */
  org.ds.paxos.TransactionOrBuilder getTOrBuilder();

  /**
   * <code>.org.ds.paxos.TimeStampProto timStamp = 2;</code>
   * @return Whether the timStamp field is set.
   */
  boolean hasTimStamp();
  /**
   * <code>.org.ds.paxos.TimeStampProto timStamp = 2;</code>
   * @return The timStamp.
   */
  org.ds.paxos.TimeStampProto getTimStamp();
  /**
   * <code>.org.ds.paxos.TimeStampProto timStamp = 2;</code>
   */
  org.ds.paxos.TimeStampProtoOrBuilder getTimStampOrBuilder();

  /**
   * <code>int32 currentLeader = 3;</code>
   * @return The currentLeader.
   */
  int getCurrentLeader();
}
