// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/Raft.proto
// Protobuf Java Version: 4.29.3

package org.ds.paxos;

public interface AckOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.ds.paxos.Ack)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * later on we can add more fields like timestamp for causal consistency
   * </pre>
   *
   * <code>repeated .org.ds.paxos.AckMessage ackMessage = 1;</code>
   */
  java.util.List<org.ds.paxos.AckMessage> 
      getAckMessageList();
  /**
   * <pre>
   * later on we can add more fields like timestamp for causal consistency
   * </pre>
   *
   * <code>repeated .org.ds.paxos.AckMessage ackMessage = 1;</code>
   */
  org.ds.paxos.AckMessage getAckMessage(int index);
  /**
   * <pre>
   * later on we can add more fields like timestamp for causal consistency
   * </pre>
   *
   * <code>repeated .org.ds.paxos.AckMessage ackMessage = 1;</code>
   */
  int getAckMessageCount();
  /**
   * <pre>
   * later on we can add more fields like timestamp for causal consistency
   * </pre>
   *
   * <code>repeated .org.ds.paxos.AckMessage ackMessage = 1;</code>
   */
  java.util.List<? extends org.ds.paxos.AckMessageOrBuilder> 
      getAckMessageOrBuilderList();
  /**
   * <pre>
   * later on we can add more fields like timestamp for causal consistency
   * </pre>
   *
   * <code>repeated .org.ds.paxos.AckMessage ackMessage = 1;</code>
   */
  org.ds.paxos.AckMessageOrBuilder getAckMessageOrBuilder(
      int index);
}
