// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/Raft.proto
// Protobuf Java Version: 4.29.3

package org.ds.paxos;

public interface AppendEntriesResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.ds.paxos.AppendEntriesResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 currentTerm = 1;</code>
   * @return The currentTerm.
   */
  int getCurrentTerm();

  /**
   * <code>bool isSuccessFull = 2;</code>
   * @return The isSuccessFull.
   */
  boolean getIsSuccessFull();

  /**
   * <code>int32 followerId = 3;</code>
   * @return The followerId.
   */
  int getFollowerId();

  /**
   * <code>.org.ds.paxos.TimeStampProto timeStamp = 4;</code>
   * @return Whether the timeStamp field is set.
   */
  boolean hasTimeStamp();
  /**
   * <code>.org.ds.paxos.TimeStampProto timeStamp = 4;</code>
   * @return The timeStamp.
   */
  org.ds.paxos.TimeStampProto getTimeStamp();
  /**
   * <code>.org.ds.paxos.TimeStampProto timeStamp = 4;</code>
   */
  org.ds.paxos.TimeStampProtoOrBuilder getTimeStampOrBuilder();
}
