// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/Raft.proto
// Protobuf Java Version: 4.29.3

package org.ds.paxos;

public interface AppendEntriesArgumentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.ds.paxos.AppendEntriesArgument)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 leadersTerm = 1;</code>
   * @return The leadersTerm.
   */
  int getLeadersTerm();

  /**
   * <code>int32 prevLogIndex = 2;</code>
   * @return The prevLogIndex.
   */
  int getPrevLogIndex();

  /**
   * <code>int32 leadersId = 3;</code>
   * @return The leadersId.
   */
  int getLeadersId();

  /**
   * <code>int32 prevLogTerm = 4;</code>
   * @return The prevLogTerm.
   */
  int getPrevLogTerm();

  /**
   * <code>.org.ds.paxos.Log entriesToAppend = 5;</code>
   * @return Whether the entriesToAppend field is set.
   */
  boolean hasEntriesToAppend();
  /**
   * <code>.org.ds.paxos.Log entriesToAppend = 5;</code>
   * @return The entriesToAppend.
   */
  org.ds.paxos.Log getEntriesToAppend();
  /**
   * <code>.org.ds.paxos.Log entriesToAppend = 5;</code>
   */
  org.ds.paxos.LogOrBuilder getEntriesToAppendOrBuilder();

  /**
   * <code>int32 leadersCommit = 6;</code>
   * @return The leadersCommit.
   */
  int getLeadersCommit();

  /**
   * <code>int32 ackIndex = 7;</code>
   * @return The ackIndex.
   */
  int getAckIndex();

  /**
   * <code>.org.ds.paxos.TimeStampProto timeStamp = 8;</code>
   * @return Whether the timeStamp field is set.
   */
  boolean hasTimeStamp();
  /**
   * <code>.org.ds.paxos.TimeStampProto timeStamp = 8;</code>
   * @return The timeStamp.
   */
  org.ds.paxos.TimeStampProto getTimeStamp();
  /**
   * <code>.org.ds.paxos.TimeStampProto timeStamp = 8;</code>
   */
  org.ds.paxos.TimeStampProtoOrBuilder getTimeStampOrBuilder();
}
