// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/Raft.proto
// Protobuf Java Version: 4.29.3

package org.ds.paxos;

/**
 * Protobuf type {@code org.ds.paxos.AppendEntriesArgument}
 */
public final class AppendEntriesArgument extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:org.ds.paxos.AppendEntriesArgument)
    AppendEntriesArgumentOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      AppendEntriesArgument.class.getName());
  }
  // Use AppendEntriesArgument.newBuilder() to construct.
  private AppendEntriesArgument(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AppendEntriesArgument() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_AppendEntriesArgument_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_AppendEntriesArgument_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.ds.paxos.AppendEntriesArgument.class, org.ds.paxos.AppendEntriesArgument.Builder.class);
  }

  private int bitField0_;
  public static final int LEADERSTERM_FIELD_NUMBER = 1;
  private int leadersTerm_ = 0;
  /**
   * <code>int32 leadersTerm = 1;</code>
   * @return The leadersTerm.
   */
  @java.lang.Override
  public int getLeadersTerm() {
    return leadersTerm_;
  }

  public static final int PREVLOGINDEX_FIELD_NUMBER = 2;
  private int prevLogIndex_ = 0;
  /**
   * <code>int32 prevLogIndex = 2;</code>
   * @return The prevLogIndex.
   */
  @java.lang.Override
  public int getPrevLogIndex() {
    return prevLogIndex_;
  }

  public static final int LEADERSID_FIELD_NUMBER = 3;
  private int leadersId_ = 0;
  /**
   * <code>int32 leadersId = 3;</code>
   * @return The leadersId.
   */
  @java.lang.Override
  public int getLeadersId() {
    return leadersId_;
  }

  public static final int PREVLOGTERM_FIELD_NUMBER = 4;
  private int prevLogTerm_ = 0;
  /**
   * <code>int32 prevLogTerm = 4;</code>
   * @return The prevLogTerm.
   */
  @java.lang.Override
  public int getPrevLogTerm() {
    return prevLogTerm_;
  }

  public static final int ENTRIESTOAPPEND_FIELD_NUMBER = 5;
  private org.ds.paxos.Log entriesToAppend_;
  /**
   * <code>.org.ds.paxos.Log entriesToAppend = 5;</code>
   * @return Whether the entriesToAppend field is set.
   */
  @java.lang.Override
  public boolean hasEntriesToAppend() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.org.ds.paxos.Log entriesToAppend = 5;</code>
   * @return The entriesToAppend.
   */
  @java.lang.Override
  public org.ds.paxos.Log getEntriesToAppend() {
    return entriesToAppend_ == null ? org.ds.paxos.Log.getDefaultInstance() : entriesToAppend_;
  }
  /**
   * <code>.org.ds.paxos.Log entriesToAppend = 5;</code>
   */
  @java.lang.Override
  public org.ds.paxos.LogOrBuilder getEntriesToAppendOrBuilder() {
    return entriesToAppend_ == null ? org.ds.paxos.Log.getDefaultInstance() : entriesToAppend_;
  }

  public static final int LEADERSCOMMIT_FIELD_NUMBER = 6;
  private int leadersCommit_ = 0;
  /**
   * <code>int32 leadersCommit = 6;</code>
   * @return The leadersCommit.
   */
  @java.lang.Override
  public int getLeadersCommit() {
    return leadersCommit_;
  }

  public static final int ACKINDEX_FIELD_NUMBER = 7;
  private int ackIndex_ = 0;
  /**
   * <code>int32 ackIndex = 7;</code>
   * @return The ackIndex.
   */
  @java.lang.Override
  public int getAckIndex() {
    return ackIndex_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 8;
  private org.ds.paxos.TimeStampProto timeStamp_;
  /**
   * <code>.org.ds.paxos.TimeStampProto timeStamp = 8;</code>
   * @return Whether the timeStamp field is set.
   */
  @java.lang.Override
  public boolean hasTimeStamp() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.org.ds.paxos.TimeStampProto timeStamp = 8;</code>
   * @return The timeStamp.
   */
  @java.lang.Override
  public org.ds.paxos.TimeStampProto getTimeStamp() {
    return timeStamp_ == null ? org.ds.paxos.TimeStampProto.getDefaultInstance() : timeStamp_;
  }
  /**
   * <code>.org.ds.paxos.TimeStampProto timeStamp = 8;</code>
   */
  @java.lang.Override
  public org.ds.paxos.TimeStampProtoOrBuilder getTimeStampOrBuilder() {
    return timeStamp_ == null ? org.ds.paxos.TimeStampProto.getDefaultInstance() : timeStamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (leadersTerm_ != 0) {
      output.writeInt32(1, leadersTerm_);
    }
    if (prevLogIndex_ != 0) {
      output.writeInt32(2, prevLogIndex_);
    }
    if (leadersId_ != 0) {
      output.writeInt32(3, leadersId_);
    }
    if (prevLogTerm_ != 0) {
      output.writeInt32(4, prevLogTerm_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(5, getEntriesToAppend());
    }
    if (leadersCommit_ != 0) {
      output.writeInt32(6, leadersCommit_);
    }
    if (ackIndex_ != 0) {
      output.writeInt32(7, ackIndex_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(8, getTimeStamp());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (leadersTerm_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, leadersTerm_);
    }
    if (prevLogIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, prevLogIndex_);
    }
    if (leadersId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, leadersId_);
    }
    if (prevLogTerm_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, prevLogTerm_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getEntriesToAppend());
    }
    if (leadersCommit_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, leadersCommit_);
    }
    if (ackIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, ackIndex_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getTimeStamp());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.ds.paxos.AppendEntriesArgument)) {
      return super.equals(obj);
    }
    org.ds.paxos.AppendEntriesArgument other = (org.ds.paxos.AppendEntriesArgument) obj;

    if (getLeadersTerm()
        != other.getLeadersTerm()) return false;
    if (getPrevLogIndex()
        != other.getPrevLogIndex()) return false;
    if (getLeadersId()
        != other.getLeadersId()) return false;
    if (getPrevLogTerm()
        != other.getPrevLogTerm()) return false;
    if (hasEntriesToAppend() != other.hasEntriesToAppend()) return false;
    if (hasEntriesToAppend()) {
      if (!getEntriesToAppend()
          .equals(other.getEntriesToAppend())) return false;
    }
    if (getLeadersCommit()
        != other.getLeadersCommit()) return false;
    if (getAckIndex()
        != other.getAckIndex()) return false;
    if (hasTimeStamp() != other.hasTimeStamp()) return false;
    if (hasTimeStamp()) {
      if (!getTimeStamp()
          .equals(other.getTimeStamp())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LEADERSTERM_FIELD_NUMBER;
    hash = (53 * hash) + getLeadersTerm();
    hash = (37 * hash) + PREVLOGINDEX_FIELD_NUMBER;
    hash = (53 * hash) + getPrevLogIndex();
    hash = (37 * hash) + LEADERSID_FIELD_NUMBER;
    hash = (53 * hash) + getLeadersId();
    hash = (37 * hash) + PREVLOGTERM_FIELD_NUMBER;
    hash = (53 * hash) + getPrevLogTerm();
    if (hasEntriesToAppend()) {
      hash = (37 * hash) + ENTRIESTOAPPEND_FIELD_NUMBER;
      hash = (53 * hash) + getEntriesToAppend().hashCode();
    }
    hash = (37 * hash) + LEADERSCOMMIT_FIELD_NUMBER;
    hash = (53 * hash) + getLeadersCommit();
    hash = (37 * hash) + ACKINDEX_FIELD_NUMBER;
    hash = (53 * hash) + getAckIndex();
    if (hasTimeStamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimeStamp().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.ds.paxos.AppendEntriesArgument parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.AppendEntriesArgument parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.AppendEntriesArgument parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.AppendEntriesArgument parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.AppendEntriesArgument parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.AppendEntriesArgument parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.AppendEntriesArgument parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.ds.paxos.AppendEntriesArgument parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.ds.paxos.AppendEntriesArgument parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.ds.paxos.AppendEntriesArgument parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.ds.paxos.AppendEntriesArgument parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.ds.paxos.AppendEntriesArgument parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.ds.paxos.AppendEntriesArgument prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.ds.paxos.AppendEntriesArgument}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.ds.paxos.AppendEntriesArgument)
      org.ds.paxos.AppendEntriesArgumentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_AppendEntriesArgument_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_AppendEntriesArgument_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.ds.paxos.AppendEntriesArgument.class, org.ds.paxos.AppendEntriesArgument.Builder.class);
    }

    // Construct using org.ds.paxos.AppendEntriesArgument.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getEntriesToAppendFieldBuilder();
        getTimeStampFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      leadersTerm_ = 0;
      prevLogIndex_ = 0;
      leadersId_ = 0;
      prevLogTerm_ = 0;
      entriesToAppend_ = null;
      if (entriesToAppendBuilder_ != null) {
        entriesToAppendBuilder_.dispose();
        entriesToAppendBuilder_ = null;
      }
      leadersCommit_ = 0;
      ackIndex_ = 0;
      timeStamp_ = null;
      if (timeStampBuilder_ != null) {
        timeStampBuilder_.dispose();
        timeStampBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_AppendEntriesArgument_descriptor;
    }

    @java.lang.Override
    public org.ds.paxos.AppendEntriesArgument getDefaultInstanceForType() {
      return org.ds.paxos.AppendEntriesArgument.getDefaultInstance();
    }

    @java.lang.Override
    public org.ds.paxos.AppendEntriesArgument build() {
      org.ds.paxos.AppendEntriesArgument result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.ds.paxos.AppendEntriesArgument buildPartial() {
      org.ds.paxos.AppendEntriesArgument result = new org.ds.paxos.AppendEntriesArgument(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.ds.paxos.AppendEntriesArgument result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.leadersTerm_ = leadersTerm_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.prevLogIndex_ = prevLogIndex_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.leadersId_ = leadersId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.prevLogTerm_ = prevLogTerm_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.entriesToAppend_ = entriesToAppendBuilder_ == null
            ? entriesToAppend_
            : entriesToAppendBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.leadersCommit_ = leadersCommit_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.ackIndex_ = ackIndex_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.timeStamp_ = timeStampBuilder_ == null
            ? timeStamp_
            : timeStampBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.ds.paxos.AppendEntriesArgument) {
        return mergeFrom((org.ds.paxos.AppendEntriesArgument)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.ds.paxos.AppendEntriesArgument other) {
      if (other == org.ds.paxos.AppendEntriesArgument.getDefaultInstance()) return this;
      if (other.getLeadersTerm() != 0) {
        setLeadersTerm(other.getLeadersTerm());
      }
      if (other.getPrevLogIndex() != 0) {
        setPrevLogIndex(other.getPrevLogIndex());
      }
      if (other.getLeadersId() != 0) {
        setLeadersId(other.getLeadersId());
      }
      if (other.getPrevLogTerm() != 0) {
        setPrevLogTerm(other.getPrevLogTerm());
      }
      if (other.hasEntriesToAppend()) {
        mergeEntriesToAppend(other.getEntriesToAppend());
      }
      if (other.getLeadersCommit() != 0) {
        setLeadersCommit(other.getLeadersCommit());
      }
      if (other.getAckIndex() != 0) {
        setAckIndex(other.getAckIndex());
      }
      if (other.hasTimeStamp()) {
        mergeTimeStamp(other.getTimeStamp());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              leadersTerm_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              prevLogIndex_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              leadersId_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              prevLogTerm_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              input.readMessage(
                  getEntriesToAppendFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              leadersCommit_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              ackIndex_ = input.readInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 66: {
              input.readMessage(
                  getTimeStampFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int leadersTerm_ ;
    /**
     * <code>int32 leadersTerm = 1;</code>
     * @return The leadersTerm.
     */
    @java.lang.Override
    public int getLeadersTerm() {
      return leadersTerm_;
    }
    /**
     * <code>int32 leadersTerm = 1;</code>
     * @param value The leadersTerm to set.
     * @return This builder for chaining.
     */
    public Builder setLeadersTerm(int value) {

      leadersTerm_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 leadersTerm = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLeadersTerm() {
      bitField0_ = (bitField0_ & ~0x00000001);
      leadersTerm_ = 0;
      onChanged();
      return this;
    }

    private int prevLogIndex_ ;
    /**
     * <code>int32 prevLogIndex = 2;</code>
     * @return The prevLogIndex.
     */
    @java.lang.Override
    public int getPrevLogIndex() {
      return prevLogIndex_;
    }
    /**
     * <code>int32 prevLogIndex = 2;</code>
     * @param value The prevLogIndex to set.
     * @return This builder for chaining.
     */
    public Builder setPrevLogIndex(int value) {

      prevLogIndex_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 prevLogIndex = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrevLogIndex() {
      bitField0_ = (bitField0_ & ~0x00000002);
      prevLogIndex_ = 0;
      onChanged();
      return this;
    }

    private int leadersId_ ;
    /**
     * <code>int32 leadersId = 3;</code>
     * @return The leadersId.
     */
    @java.lang.Override
    public int getLeadersId() {
      return leadersId_;
    }
    /**
     * <code>int32 leadersId = 3;</code>
     * @param value The leadersId to set.
     * @return This builder for chaining.
     */
    public Builder setLeadersId(int value) {

      leadersId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 leadersId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLeadersId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      leadersId_ = 0;
      onChanged();
      return this;
    }

    private int prevLogTerm_ ;
    /**
     * <code>int32 prevLogTerm = 4;</code>
     * @return The prevLogTerm.
     */
    @java.lang.Override
    public int getPrevLogTerm() {
      return prevLogTerm_;
    }
    /**
     * <code>int32 prevLogTerm = 4;</code>
     * @param value The prevLogTerm to set.
     * @return This builder for chaining.
     */
    public Builder setPrevLogTerm(int value) {

      prevLogTerm_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 prevLogTerm = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrevLogTerm() {
      bitField0_ = (bitField0_ & ~0x00000008);
      prevLogTerm_ = 0;
      onChanged();
      return this;
    }

    private org.ds.paxos.Log entriesToAppend_;
    private com.google.protobuf.SingleFieldBuilder<
        org.ds.paxos.Log, org.ds.paxos.Log.Builder, org.ds.paxos.LogOrBuilder> entriesToAppendBuilder_;
    /**
     * <code>.org.ds.paxos.Log entriesToAppend = 5;</code>
     * @return Whether the entriesToAppend field is set.
     */
    public boolean hasEntriesToAppend() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.org.ds.paxos.Log entriesToAppend = 5;</code>
     * @return The entriesToAppend.
     */
    public org.ds.paxos.Log getEntriesToAppend() {
      if (entriesToAppendBuilder_ == null) {
        return entriesToAppend_ == null ? org.ds.paxos.Log.getDefaultInstance() : entriesToAppend_;
      } else {
        return entriesToAppendBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.ds.paxos.Log entriesToAppend = 5;</code>
     */
    public Builder setEntriesToAppend(org.ds.paxos.Log value) {
      if (entriesToAppendBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        entriesToAppend_ = value;
      } else {
        entriesToAppendBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.org.ds.paxos.Log entriesToAppend = 5;</code>
     */
    public Builder setEntriesToAppend(
        org.ds.paxos.Log.Builder builderForValue) {
      if (entriesToAppendBuilder_ == null) {
        entriesToAppend_ = builderForValue.build();
      } else {
        entriesToAppendBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.org.ds.paxos.Log entriesToAppend = 5;</code>
     */
    public Builder mergeEntriesToAppend(org.ds.paxos.Log value) {
      if (entriesToAppendBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          entriesToAppend_ != null &&
          entriesToAppend_ != org.ds.paxos.Log.getDefaultInstance()) {
          getEntriesToAppendBuilder().mergeFrom(value);
        } else {
          entriesToAppend_ = value;
        }
      } else {
        entriesToAppendBuilder_.mergeFrom(value);
      }
      if (entriesToAppend_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.org.ds.paxos.Log entriesToAppend = 5;</code>
     */
    public Builder clearEntriesToAppend() {
      bitField0_ = (bitField0_ & ~0x00000010);
      entriesToAppend_ = null;
      if (entriesToAppendBuilder_ != null) {
        entriesToAppendBuilder_.dispose();
        entriesToAppendBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.org.ds.paxos.Log entriesToAppend = 5;</code>
     */
    public org.ds.paxos.Log.Builder getEntriesToAppendBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getEntriesToAppendFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.ds.paxos.Log entriesToAppend = 5;</code>
     */
    public org.ds.paxos.LogOrBuilder getEntriesToAppendOrBuilder() {
      if (entriesToAppendBuilder_ != null) {
        return entriesToAppendBuilder_.getMessageOrBuilder();
      } else {
        return entriesToAppend_ == null ?
            org.ds.paxos.Log.getDefaultInstance() : entriesToAppend_;
      }
    }
    /**
     * <code>.org.ds.paxos.Log entriesToAppend = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.ds.paxos.Log, org.ds.paxos.Log.Builder, org.ds.paxos.LogOrBuilder> 
        getEntriesToAppendFieldBuilder() {
      if (entriesToAppendBuilder_ == null) {
        entriesToAppendBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.ds.paxos.Log, org.ds.paxos.Log.Builder, org.ds.paxos.LogOrBuilder>(
                getEntriesToAppend(),
                getParentForChildren(),
                isClean());
        entriesToAppend_ = null;
      }
      return entriesToAppendBuilder_;
    }

    private int leadersCommit_ ;
    /**
     * <code>int32 leadersCommit = 6;</code>
     * @return The leadersCommit.
     */
    @java.lang.Override
    public int getLeadersCommit() {
      return leadersCommit_;
    }
    /**
     * <code>int32 leadersCommit = 6;</code>
     * @param value The leadersCommit to set.
     * @return This builder for chaining.
     */
    public Builder setLeadersCommit(int value) {

      leadersCommit_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 leadersCommit = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearLeadersCommit() {
      bitField0_ = (bitField0_ & ~0x00000020);
      leadersCommit_ = 0;
      onChanged();
      return this;
    }

    private int ackIndex_ ;
    /**
     * <code>int32 ackIndex = 7;</code>
     * @return The ackIndex.
     */
    @java.lang.Override
    public int getAckIndex() {
      return ackIndex_;
    }
    /**
     * <code>int32 ackIndex = 7;</code>
     * @param value The ackIndex to set.
     * @return This builder for chaining.
     */
    public Builder setAckIndex(int value) {

      ackIndex_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int32 ackIndex = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearAckIndex() {
      bitField0_ = (bitField0_ & ~0x00000040);
      ackIndex_ = 0;
      onChanged();
      return this;
    }

    private org.ds.paxos.TimeStampProto timeStamp_;
    private com.google.protobuf.SingleFieldBuilder<
        org.ds.paxos.TimeStampProto, org.ds.paxos.TimeStampProto.Builder, org.ds.paxos.TimeStampProtoOrBuilder> timeStampBuilder_;
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 8;</code>
     * @return Whether the timeStamp field is set.
     */
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 8;</code>
     * @return The timeStamp.
     */
    public org.ds.paxos.TimeStampProto getTimeStamp() {
      if (timeStampBuilder_ == null) {
        return timeStamp_ == null ? org.ds.paxos.TimeStampProto.getDefaultInstance() : timeStamp_;
      } else {
        return timeStampBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 8;</code>
     */
    public Builder setTimeStamp(org.ds.paxos.TimeStampProto value) {
      if (timeStampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timeStamp_ = value;
      } else {
        timeStampBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 8;</code>
     */
    public Builder setTimeStamp(
        org.ds.paxos.TimeStampProto.Builder builderForValue) {
      if (timeStampBuilder_ == null) {
        timeStamp_ = builderForValue.build();
      } else {
        timeStampBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 8;</code>
     */
    public Builder mergeTimeStamp(org.ds.paxos.TimeStampProto value) {
      if (timeStampBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0) &&
          timeStamp_ != null &&
          timeStamp_ != org.ds.paxos.TimeStampProto.getDefaultInstance()) {
          getTimeStampBuilder().mergeFrom(value);
        } else {
          timeStamp_ = value;
        }
      } else {
        timeStampBuilder_.mergeFrom(value);
      }
      if (timeStamp_ != null) {
        bitField0_ |= 0x00000080;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 8;</code>
     */
    public Builder clearTimeStamp() {
      bitField0_ = (bitField0_ & ~0x00000080);
      timeStamp_ = null;
      if (timeStampBuilder_ != null) {
        timeStampBuilder_.dispose();
        timeStampBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 8;</code>
     */
    public org.ds.paxos.TimeStampProto.Builder getTimeStampBuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return getTimeStampFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 8;</code>
     */
    public org.ds.paxos.TimeStampProtoOrBuilder getTimeStampOrBuilder() {
      if (timeStampBuilder_ != null) {
        return timeStampBuilder_.getMessageOrBuilder();
      } else {
        return timeStamp_ == null ?
            org.ds.paxos.TimeStampProto.getDefaultInstance() : timeStamp_;
      }
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.ds.paxos.TimeStampProto, org.ds.paxos.TimeStampProto.Builder, org.ds.paxos.TimeStampProtoOrBuilder> 
        getTimeStampFieldBuilder() {
      if (timeStampBuilder_ == null) {
        timeStampBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.ds.paxos.TimeStampProto, org.ds.paxos.TimeStampProto.Builder, org.ds.paxos.TimeStampProtoOrBuilder>(
                getTimeStamp(),
                getParentForChildren(),
                isClean());
        timeStamp_ = null;
      }
      return timeStampBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:org.ds.paxos.AppendEntriesArgument)
  }

  // @@protoc_insertion_point(class_scope:org.ds.paxos.AppendEntriesArgument)
  private static final org.ds.paxos.AppendEntriesArgument DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.ds.paxos.AppendEntriesArgument();
  }

  public static org.ds.paxos.AppendEntriesArgument getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AppendEntriesArgument>
      PARSER = new com.google.protobuf.AbstractParser<AppendEntriesArgument>() {
    @java.lang.Override
    public AppendEntriesArgument parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AppendEntriesArgument> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AppendEntriesArgument> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.ds.paxos.AppendEntriesArgument getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

