// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/Raft.proto
// Protobuf Java Version: 4.29.3

package org.ds.paxos;

/**
 * Protobuf type {@code org.ds.paxos.AppendEntriesResult}
 */
public final class AppendEntriesResult extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:org.ds.paxos.AppendEntriesResult)
    AppendEntriesResultOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      AppendEntriesResult.class.getName());
  }
  // Use AppendEntriesResult.newBuilder() to construct.
  private AppendEntriesResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AppendEntriesResult() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_AppendEntriesResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_AppendEntriesResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.ds.paxos.AppendEntriesResult.class, org.ds.paxos.AppendEntriesResult.Builder.class);
  }

  private int bitField0_;
  public static final int CURRENTTERM_FIELD_NUMBER = 1;
  private int currentTerm_ = 0;
  /**
   * <code>int32 currentTerm = 1;</code>
   * @return The currentTerm.
   */
  @java.lang.Override
  public int getCurrentTerm() {
    return currentTerm_;
  }

  public static final int ISSUCCESSFULL_FIELD_NUMBER = 2;
  private boolean isSuccessFull_ = false;
  /**
   * <code>bool isSuccessFull = 2;</code>
   * @return The isSuccessFull.
   */
  @java.lang.Override
  public boolean getIsSuccessFull() {
    return isSuccessFull_;
  }

  public static final int FOLLOWERID_FIELD_NUMBER = 3;
  private int followerId_ = 0;
  /**
   * <code>int32 followerId = 3;</code>
   * @return The followerId.
   */
  @java.lang.Override
  public int getFollowerId() {
    return followerId_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 4;
  private org.ds.paxos.TimeStampProto timeStamp_;
  /**
   * <code>.org.ds.paxos.TimeStampProto timeStamp = 4;</code>
   * @return Whether the timeStamp field is set.
   */
  @java.lang.Override
  public boolean hasTimeStamp() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.org.ds.paxos.TimeStampProto timeStamp = 4;</code>
   * @return The timeStamp.
   */
  @java.lang.Override
  public org.ds.paxos.TimeStampProto getTimeStamp() {
    return timeStamp_ == null ? org.ds.paxos.TimeStampProto.getDefaultInstance() : timeStamp_;
  }
  /**
   * <code>.org.ds.paxos.TimeStampProto timeStamp = 4;</code>
   */
  @java.lang.Override
  public org.ds.paxos.TimeStampProtoOrBuilder getTimeStampOrBuilder() {
    return timeStamp_ == null ? org.ds.paxos.TimeStampProto.getDefaultInstance() : timeStamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (currentTerm_ != 0) {
      output.writeInt32(1, currentTerm_);
    }
    if (isSuccessFull_ != false) {
      output.writeBool(2, isSuccessFull_);
    }
    if (followerId_ != 0) {
      output.writeInt32(3, followerId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(4, getTimeStamp());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (currentTerm_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, currentTerm_);
    }
    if (isSuccessFull_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, isSuccessFull_);
    }
    if (followerId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, followerId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getTimeStamp());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.ds.paxos.AppendEntriesResult)) {
      return super.equals(obj);
    }
    org.ds.paxos.AppendEntriesResult other = (org.ds.paxos.AppendEntriesResult) obj;

    if (getCurrentTerm()
        != other.getCurrentTerm()) return false;
    if (getIsSuccessFull()
        != other.getIsSuccessFull()) return false;
    if (getFollowerId()
        != other.getFollowerId()) return false;
    if (hasTimeStamp() != other.hasTimeStamp()) return false;
    if (hasTimeStamp()) {
      if (!getTimeStamp()
          .equals(other.getTimeStamp())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CURRENTTERM_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentTerm();
    hash = (37 * hash) + ISSUCCESSFULL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsSuccessFull());
    hash = (37 * hash) + FOLLOWERID_FIELD_NUMBER;
    hash = (53 * hash) + getFollowerId();
    if (hasTimeStamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimeStamp().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.ds.paxos.AppendEntriesResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.AppendEntriesResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.AppendEntriesResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.AppendEntriesResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.AppendEntriesResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.AppendEntriesResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.AppendEntriesResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.ds.paxos.AppendEntriesResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.ds.paxos.AppendEntriesResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.ds.paxos.AppendEntriesResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.ds.paxos.AppendEntriesResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.ds.paxos.AppendEntriesResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.ds.paxos.AppendEntriesResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.ds.paxos.AppendEntriesResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.ds.paxos.AppendEntriesResult)
      org.ds.paxos.AppendEntriesResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_AppendEntriesResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_AppendEntriesResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.ds.paxos.AppendEntriesResult.class, org.ds.paxos.AppendEntriesResult.Builder.class);
    }

    // Construct using org.ds.paxos.AppendEntriesResult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getTimeStampFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      currentTerm_ = 0;
      isSuccessFull_ = false;
      followerId_ = 0;
      timeStamp_ = null;
      if (timeStampBuilder_ != null) {
        timeStampBuilder_.dispose();
        timeStampBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_AppendEntriesResult_descriptor;
    }

    @java.lang.Override
    public org.ds.paxos.AppendEntriesResult getDefaultInstanceForType() {
      return org.ds.paxos.AppendEntriesResult.getDefaultInstance();
    }

    @java.lang.Override
    public org.ds.paxos.AppendEntriesResult build() {
      org.ds.paxos.AppendEntriesResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.ds.paxos.AppendEntriesResult buildPartial() {
      org.ds.paxos.AppendEntriesResult result = new org.ds.paxos.AppendEntriesResult(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.ds.paxos.AppendEntriesResult result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.currentTerm_ = currentTerm_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.isSuccessFull_ = isSuccessFull_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.followerId_ = followerId_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.timeStamp_ = timeStampBuilder_ == null
            ? timeStamp_
            : timeStampBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.ds.paxos.AppendEntriesResult) {
        return mergeFrom((org.ds.paxos.AppendEntriesResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.ds.paxos.AppendEntriesResult other) {
      if (other == org.ds.paxos.AppendEntriesResult.getDefaultInstance()) return this;
      if (other.getCurrentTerm() != 0) {
        setCurrentTerm(other.getCurrentTerm());
      }
      if (other.getIsSuccessFull() != false) {
        setIsSuccessFull(other.getIsSuccessFull());
      }
      if (other.getFollowerId() != 0) {
        setFollowerId(other.getFollowerId());
      }
      if (other.hasTimeStamp()) {
        mergeTimeStamp(other.getTimeStamp());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              currentTerm_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              isSuccessFull_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              followerId_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              input.readMessage(
                  getTimeStampFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int currentTerm_ ;
    /**
     * <code>int32 currentTerm = 1;</code>
     * @return The currentTerm.
     */
    @java.lang.Override
    public int getCurrentTerm() {
      return currentTerm_;
    }
    /**
     * <code>int32 currentTerm = 1;</code>
     * @param value The currentTerm to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentTerm(int value) {

      currentTerm_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 currentTerm = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentTerm() {
      bitField0_ = (bitField0_ & ~0x00000001);
      currentTerm_ = 0;
      onChanged();
      return this;
    }

    private boolean isSuccessFull_ ;
    /**
     * <code>bool isSuccessFull = 2;</code>
     * @return The isSuccessFull.
     */
    @java.lang.Override
    public boolean getIsSuccessFull() {
      return isSuccessFull_;
    }
    /**
     * <code>bool isSuccessFull = 2;</code>
     * @param value The isSuccessFull to set.
     * @return This builder for chaining.
     */
    public Builder setIsSuccessFull(boolean value) {

      isSuccessFull_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool isSuccessFull = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsSuccessFull() {
      bitField0_ = (bitField0_ & ~0x00000002);
      isSuccessFull_ = false;
      onChanged();
      return this;
    }

    private int followerId_ ;
    /**
     * <code>int32 followerId = 3;</code>
     * @return The followerId.
     */
    @java.lang.Override
    public int getFollowerId() {
      return followerId_;
    }
    /**
     * <code>int32 followerId = 3;</code>
     * @param value The followerId to set.
     * @return This builder for chaining.
     */
    public Builder setFollowerId(int value) {

      followerId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 followerId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFollowerId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      followerId_ = 0;
      onChanged();
      return this;
    }

    private org.ds.paxos.TimeStampProto timeStamp_;
    private com.google.protobuf.SingleFieldBuilder<
        org.ds.paxos.TimeStampProto, org.ds.paxos.TimeStampProto.Builder, org.ds.paxos.TimeStampProtoOrBuilder> timeStampBuilder_;
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 4;</code>
     * @return Whether the timeStamp field is set.
     */
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 4;</code>
     * @return The timeStamp.
     */
    public org.ds.paxos.TimeStampProto getTimeStamp() {
      if (timeStampBuilder_ == null) {
        return timeStamp_ == null ? org.ds.paxos.TimeStampProto.getDefaultInstance() : timeStamp_;
      } else {
        return timeStampBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 4;</code>
     */
    public Builder setTimeStamp(org.ds.paxos.TimeStampProto value) {
      if (timeStampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timeStamp_ = value;
      } else {
        timeStampBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 4;</code>
     */
    public Builder setTimeStamp(
        org.ds.paxos.TimeStampProto.Builder builderForValue) {
      if (timeStampBuilder_ == null) {
        timeStamp_ = builderForValue.build();
      } else {
        timeStampBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 4;</code>
     */
    public Builder mergeTimeStamp(org.ds.paxos.TimeStampProto value) {
      if (timeStampBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          timeStamp_ != null &&
          timeStamp_ != org.ds.paxos.TimeStampProto.getDefaultInstance()) {
          getTimeStampBuilder().mergeFrom(value);
        } else {
          timeStamp_ = value;
        }
      } else {
        timeStampBuilder_.mergeFrom(value);
      }
      if (timeStamp_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 4;</code>
     */
    public Builder clearTimeStamp() {
      bitField0_ = (bitField0_ & ~0x00000008);
      timeStamp_ = null;
      if (timeStampBuilder_ != null) {
        timeStampBuilder_.dispose();
        timeStampBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 4;</code>
     */
    public org.ds.paxos.TimeStampProto.Builder getTimeStampBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getTimeStampFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 4;</code>
     */
    public org.ds.paxos.TimeStampProtoOrBuilder getTimeStampOrBuilder() {
      if (timeStampBuilder_ != null) {
        return timeStampBuilder_.getMessageOrBuilder();
      } else {
        return timeStamp_ == null ?
            org.ds.paxos.TimeStampProto.getDefaultInstance() : timeStamp_;
      }
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.ds.paxos.TimeStampProto, org.ds.paxos.TimeStampProto.Builder, org.ds.paxos.TimeStampProtoOrBuilder> 
        getTimeStampFieldBuilder() {
      if (timeStampBuilder_ == null) {
        timeStampBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.ds.paxos.TimeStampProto, org.ds.paxos.TimeStampProto.Builder, org.ds.paxos.TimeStampProtoOrBuilder>(
                getTimeStamp(),
                getParentForChildren(),
                isClean());
        timeStamp_ = null;
      }
      return timeStampBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:org.ds.paxos.AppendEntriesResult)
  }

  // @@protoc_insertion_point(class_scope:org.ds.paxos.AppendEntriesResult)
  private static final org.ds.paxos.AppendEntriesResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.ds.paxos.AppendEntriesResult();
  }

  public static org.ds.paxos.AppendEntriesResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AppendEntriesResult>
      PARSER = new com.google.protobuf.AbstractParser<AppendEntriesResult>() {
    @java.lang.Override
    public AppendEntriesResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AppendEntriesResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AppendEntriesResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.ds.paxos.AppendEntriesResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

