// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/Raft.proto
// Protobuf Java Version: 4.29.3

package org.ds.paxos;

/**
 * Protobuf type {@code org.ds.paxos.Balance}
 */
public final class Balance extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:org.ds.paxos.Balance)
    BalanceOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Balance.class.getName());
  }
  // Use Balance.newBuilder() to construct.
  private Balance(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Balance() {
    accName_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_Balance_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_Balance_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.ds.paxos.Balance.class, org.ds.paxos.Balance.Builder.class);
  }

  public static final int BALANCE_FIELD_NUMBER = 1;
  private double balance_ = 0D;
  /**
   * <code>double balance = 1;</code>
   * @return The balance.
   */
  @java.lang.Override
  public double getBalance() {
    return balance_;
  }

  public static final int ACCNAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object accName_ = "";
  /**
   * <code>string accName = 2;</code>
   * @return The accName.
   */
  @java.lang.Override
  public java.lang.String getAccName() {
    java.lang.Object ref = accName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      accName_ = s;
      return s;
    }
  }
  /**
   * <code>string accName = 2;</code>
   * @return The bytes for accName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAccNameBytes() {
    java.lang.Object ref = accName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FAILURE_FIELD_NUMBER = 3;
  private boolean failure_ = false;
  /**
   * <code>bool failure = 3;</code>
   * @return The failure.
   */
  @java.lang.Override
  public boolean getFailure() {
    return failure_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Double.doubleToRawLongBits(balance_) != 0) {
      output.writeDouble(1, balance_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(accName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, accName_);
    }
    if (failure_ != false) {
      output.writeBool(3, failure_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Double.doubleToRawLongBits(balance_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, balance_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(accName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, accName_);
    }
    if (failure_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, failure_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.ds.paxos.Balance)) {
      return super.equals(obj);
    }
    org.ds.paxos.Balance other = (org.ds.paxos.Balance) obj;

    if (java.lang.Double.doubleToLongBits(getBalance())
        != java.lang.Double.doubleToLongBits(
            other.getBalance())) return false;
    if (!getAccName()
        .equals(other.getAccName())) return false;
    if (getFailure()
        != other.getFailure()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BALANCE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getBalance()));
    hash = (37 * hash) + ACCNAME_FIELD_NUMBER;
    hash = (53 * hash) + getAccName().hashCode();
    hash = (37 * hash) + FAILURE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getFailure());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.ds.paxos.Balance parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.Balance parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.Balance parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.Balance parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.Balance parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.Balance parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.Balance parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.ds.paxos.Balance parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.ds.paxos.Balance parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.ds.paxos.Balance parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.ds.paxos.Balance parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.ds.paxos.Balance parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.ds.paxos.Balance prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.ds.paxos.Balance}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.ds.paxos.Balance)
      org.ds.paxos.BalanceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_Balance_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_Balance_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.ds.paxos.Balance.class, org.ds.paxos.Balance.Builder.class);
    }

    // Construct using org.ds.paxos.Balance.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      balance_ = 0D;
      accName_ = "";
      failure_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_Balance_descriptor;
    }

    @java.lang.Override
    public org.ds.paxos.Balance getDefaultInstanceForType() {
      return org.ds.paxos.Balance.getDefaultInstance();
    }

    @java.lang.Override
    public org.ds.paxos.Balance build() {
      org.ds.paxos.Balance result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.ds.paxos.Balance buildPartial() {
      org.ds.paxos.Balance result = new org.ds.paxos.Balance(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.ds.paxos.Balance result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.balance_ = balance_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.accName_ = accName_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.failure_ = failure_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.ds.paxos.Balance) {
        return mergeFrom((org.ds.paxos.Balance)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.ds.paxos.Balance other) {
      if (other == org.ds.paxos.Balance.getDefaultInstance()) return this;
      if (other.getBalance() != 0D) {
        setBalance(other.getBalance());
      }
      if (!other.getAccName().isEmpty()) {
        accName_ = other.accName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getFailure() != false) {
        setFailure(other.getFailure());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              balance_ = input.readDouble();
              bitField0_ |= 0x00000001;
              break;
            } // case 9
            case 18: {
              accName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              failure_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private double balance_ ;
    /**
     * <code>double balance = 1;</code>
     * @return The balance.
     */
    @java.lang.Override
    public double getBalance() {
      return balance_;
    }
    /**
     * <code>double balance = 1;</code>
     * @param value The balance to set.
     * @return This builder for chaining.
     */
    public Builder setBalance(double value) {

      balance_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>double balance = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBalance() {
      bitField0_ = (bitField0_ & ~0x00000001);
      balance_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object accName_ = "";
    /**
     * <code>string accName = 2;</code>
     * @return The accName.
     */
    public java.lang.String getAccName() {
      java.lang.Object ref = accName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string accName = 2;</code>
     * @return The bytes for accName.
     */
    public com.google.protobuf.ByteString
        getAccNameBytes() {
      java.lang.Object ref = accName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string accName = 2;</code>
     * @param value The accName to set.
     * @return This builder for chaining.
     */
    public Builder setAccName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      accName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string accName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccName() {
      accName_ = getDefaultInstance().getAccName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string accName = 2;</code>
     * @param value The bytes for accName to set.
     * @return This builder for chaining.
     */
    public Builder setAccNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      accName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private boolean failure_ ;
    /**
     * <code>bool failure = 3;</code>
     * @return The failure.
     */
    @java.lang.Override
    public boolean getFailure() {
      return failure_;
    }
    /**
     * <code>bool failure = 3;</code>
     * @param value The failure to set.
     * @return This builder for chaining.
     */
    public Builder setFailure(boolean value) {

      failure_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bool failure = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFailure() {
      bitField0_ = (bitField0_ & ~0x00000004);
      failure_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:org.ds.paxos.Balance)
  }

  // @@protoc_insertion_point(class_scope:org.ds.paxos.Balance)
  private static final org.ds.paxos.Balance DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.ds.paxos.Balance();
  }

  public static org.ds.paxos.Balance getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Balance>
      PARSER = new com.google.protobuf.AbstractParser<Balance>() {
    @java.lang.Override
    public Balance parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Balance> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Balance> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.ds.paxos.Balance getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

