// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/Raft.proto
// Protobuf Java Version: 4.29.3

package org.ds.paxos;

public interface BalanceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.ds.paxos.Balance)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double balance = 1;</code>
   * @return The balance.
   */
  double getBalance();

  /**
   * <code>string accName = 2;</code>
   * @return The accName.
   */
  java.lang.String getAccName();
  /**
   * <code>string accName = 2;</code>
   * @return The bytes for accName.
   */
  com.google.protobuf.ByteString
      getAccNameBytes();

  /**
   * <code>bool failure = 3;</code>
   * @return The failure.
   */
  boolean getFailure();
}
