// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/Raft.proto
// Protobuf Java Version: 4.29.3

package org.ds.paxos;

/**
 * Protobuf type {@code org.ds.paxos.ClientMessage}
 */
public final class ClientMessage extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:org.ds.paxos.ClientMessage)
    ClientMessageOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      ClientMessage.class.getName());
  }
  // Use ClientMessage.newBuilder() to construct.
  private ClientMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ClientMessage() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_ClientMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_ClientMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.ds.paxos.ClientMessage.class, org.ds.paxos.ClientMessage.Builder.class);
  }

  private int bitField0_;
  public static final int T_FIELD_NUMBER = 1;
  private org.ds.paxos.Transaction t_;
  /**
   * <code>.org.ds.paxos.Transaction t = 1;</code>
   * @return Whether the t field is set.
   */
  @java.lang.Override
  public boolean hasT() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.org.ds.paxos.Transaction t = 1;</code>
   * @return The t.
   */
  @java.lang.Override
  public org.ds.paxos.Transaction getT() {
    return t_ == null ? org.ds.paxos.Transaction.getDefaultInstance() : t_;
  }
  /**
   * <code>.org.ds.paxos.Transaction t = 1;</code>
   */
  @java.lang.Override
  public org.ds.paxos.TransactionOrBuilder getTOrBuilder() {
    return t_ == null ? org.ds.paxos.Transaction.getDefaultInstance() : t_;
  }

  public static final int WRITECONCERN_FIELD_NUMBER = 2;
  private int writeConcern_ = 0;
  /**
   * <code>int32 writeConcern = 2;</code>
   * @return The writeConcern.
   */
  @java.lang.Override
  public int getWriteConcern() {
    return writeConcern_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 3;
  private org.ds.paxos.TimeStampProto timeStamp_;
  /**
   * <code>.org.ds.paxos.TimeStampProto timeStamp = 3;</code>
   * @return Whether the timeStamp field is set.
   */
  @java.lang.Override
  public boolean hasTimeStamp() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.org.ds.paxos.TimeStampProto timeStamp = 3;</code>
   * @return The timeStamp.
   */
  @java.lang.Override
  public org.ds.paxos.TimeStampProto getTimeStamp() {
    return timeStamp_ == null ? org.ds.paxos.TimeStampProto.getDefaultInstance() : timeStamp_;
  }
  /**
   * <code>.org.ds.paxos.TimeStampProto timeStamp = 3;</code>
   */
  @java.lang.Override
  public org.ds.paxos.TimeStampProtoOrBuilder getTimeStampOrBuilder() {
    return timeStamp_ == null ? org.ds.paxos.TimeStampProto.getDefaultInstance() : timeStamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getT());
    }
    if (writeConcern_ != 0) {
      output.writeInt32(2, writeConcern_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getTimeStamp());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getT());
    }
    if (writeConcern_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, writeConcern_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getTimeStamp());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.ds.paxos.ClientMessage)) {
      return super.equals(obj);
    }
    org.ds.paxos.ClientMessage other = (org.ds.paxos.ClientMessage) obj;

    if (hasT() != other.hasT()) return false;
    if (hasT()) {
      if (!getT()
          .equals(other.getT())) return false;
    }
    if (getWriteConcern()
        != other.getWriteConcern()) return false;
    if (hasTimeStamp() != other.hasTimeStamp()) return false;
    if (hasTimeStamp()) {
      if (!getTimeStamp()
          .equals(other.getTimeStamp())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasT()) {
      hash = (37 * hash) + T_FIELD_NUMBER;
      hash = (53 * hash) + getT().hashCode();
    }
    hash = (37 * hash) + WRITECONCERN_FIELD_NUMBER;
    hash = (53 * hash) + getWriteConcern();
    if (hasTimeStamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimeStamp().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.ds.paxos.ClientMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.ClientMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.ClientMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.ClientMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.ClientMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.ClientMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.ClientMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.ds.paxos.ClientMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.ds.paxos.ClientMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.ds.paxos.ClientMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.ds.paxos.ClientMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.ds.paxos.ClientMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.ds.paxos.ClientMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.ds.paxos.ClientMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.ds.paxos.ClientMessage)
      org.ds.paxos.ClientMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_ClientMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_ClientMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.ds.paxos.ClientMessage.class, org.ds.paxos.ClientMessage.Builder.class);
    }

    // Construct using org.ds.paxos.ClientMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getTFieldBuilder();
        getTimeStampFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      t_ = null;
      if (tBuilder_ != null) {
        tBuilder_.dispose();
        tBuilder_ = null;
      }
      writeConcern_ = 0;
      timeStamp_ = null;
      if (timeStampBuilder_ != null) {
        timeStampBuilder_.dispose();
        timeStampBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_ClientMessage_descriptor;
    }

    @java.lang.Override
    public org.ds.paxos.ClientMessage getDefaultInstanceForType() {
      return org.ds.paxos.ClientMessage.getDefaultInstance();
    }

    @java.lang.Override
    public org.ds.paxos.ClientMessage build() {
      org.ds.paxos.ClientMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.ds.paxos.ClientMessage buildPartial() {
      org.ds.paxos.ClientMessage result = new org.ds.paxos.ClientMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.ds.paxos.ClientMessage result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.t_ = tBuilder_ == null
            ? t_
            : tBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.writeConcern_ = writeConcern_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.timeStamp_ = timeStampBuilder_ == null
            ? timeStamp_
            : timeStampBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.ds.paxos.ClientMessage) {
        return mergeFrom((org.ds.paxos.ClientMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.ds.paxos.ClientMessage other) {
      if (other == org.ds.paxos.ClientMessage.getDefaultInstance()) return this;
      if (other.hasT()) {
        mergeT(other.getT());
      }
      if (other.getWriteConcern() != 0) {
        setWriteConcern(other.getWriteConcern());
      }
      if (other.hasTimeStamp()) {
        mergeTimeStamp(other.getTimeStamp());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getTFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              writeConcern_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  getTimeStampFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private org.ds.paxos.Transaction t_;
    private com.google.protobuf.SingleFieldBuilder<
        org.ds.paxos.Transaction, org.ds.paxos.Transaction.Builder, org.ds.paxos.TransactionOrBuilder> tBuilder_;
    /**
     * <code>.org.ds.paxos.Transaction t = 1;</code>
     * @return Whether the t field is set.
     */
    public boolean hasT() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.org.ds.paxos.Transaction t = 1;</code>
     * @return The t.
     */
    public org.ds.paxos.Transaction getT() {
      if (tBuilder_ == null) {
        return t_ == null ? org.ds.paxos.Transaction.getDefaultInstance() : t_;
      } else {
        return tBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.ds.paxos.Transaction t = 1;</code>
     */
    public Builder setT(org.ds.paxos.Transaction value) {
      if (tBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        t_ = value;
      } else {
        tBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.org.ds.paxos.Transaction t = 1;</code>
     */
    public Builder setT(
        org.ds.paxos.Transaction.Builder builderForValue) {
      if (tBuilder_ == null) {
        t_ = builderForValue.build();
      } else {
        tBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.org.ds.paxos.Transaction t = 1;</code>
     */
    public Builder mergeT(org.ds.paxos.Transaction value) {
      if (tBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          t_ != null &&
          t_ != org.ds.paxos.Transaction.getDefaultInstance()) {
          getTBuilder().mergeFrom(value);
        } else {
          t_ = value;
        }
      } else {
        tBuilder_.mergeFrom(value);
      }
      if (t_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.org.ds.paxos.Transaction t = 1;</code>
     */
    public Builder clearT() {
      bitField0_ = (bitField0_ & ~0x00000001);
      t_ = null;
      if (tBuilder_ != null) {
        tBuilder_.dispose();
        tBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.org.ds.paxos.Transaction t = 1;</code>
     */
    public org.ds.paxos.Transaction.Builder getTBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getTFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.ds.paxos.Transaction t = 1;</code>
     */
    public org.ds.paxos.TransactionOrBuilder getTOrBuilder() {
      if (tBuilder_ != null) {
        return tBuilder_.getMessageOrBuilder();
      } else {
        return t_ == null ?
            org.ds.paxos.Transaction.getDefaultInstance() : t_;
      }
    }
    /**
     * <code>.org.ds.paxos.Transaction t = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.ds.paxos.Transaction, org.ds.paxos.Transaction.Builder, org.ds.paxos.TransactionOrBuilder> 
        getTFieldBuilder() {
      if (tBuilder_ == null) {
        tBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.ds.paxos.Transaction, org.ds.paxos.Transaction.Builder, org.ds.paxos.TransactionOrBuilder>(
                getT(),
                getParentForChildren(),
                isClean());
        t_ = null;
      }
      return tBuilder_;
    }

    private int writeConcern_ ;
    /**
     * <code>int32 writeConcern = 2;</code>
     * @return The writeConcern.
     */
    @java.lang.Override
    public int getWriteConcern() {
      return writeConcern_;
    }
    /**
     * <code>int32 writeConcern = 2;</code>
     * @param value The writeConcern to set.
     * @return This builder for chaining.
     */
    public Builder setWriteConcern(int value) {

      writeConcern_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 writeConcern = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearWriteConcern() {
      bitField0_ = (bitField0_ & ~0x00000002);
      writeConcern_ = 0;
      onChanged();
      return this;
    }

    private org.ds.paxos.TimeStampProto timeStamp_;
    private com.google.protobuf.SingleFieldBuilder<
        org.ds.paxos.TimeStampProto, org.ds.paxos.TimeStampProto.Builder, org.ds.paxos.TimeStampProtoOrBuilder> timeStampBuilder_;
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 3;</code>
     * @return Whether the timeStamp field is set.
     */
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 3;</code>
     * @return The timeStamp.
     */
    public org.ds.paxos.TimeStampProto getTimeStamp() {
      if (timeStampBuilder_ == null) {
        return timeStamp_ == null ? org.ds.paxos.TimeStampProto.getDefaultInstance() : timeStamp_;
      } else {
        return timeStampBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 3;</code>
     */
    public Builder setTimeStamp(org.ds.paxos.TimeStampProto value) {
      if (timeStampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timeStamp_ = value;
      } else {
        timeStampBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 3;</code>
     */
    public Builder setTimeStamp(
        org.ds.paxos.TimeStampProto.Builder builderForValue) {
      if (timeStampBuilder_ == null) {
        timeStamp_ = builderForValue.build();
      } else {
        timeStampBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 3;</code>
     */
    public Builder mergeTimeStamp(org.ds.paxos.TimeStampProto value) {
      if (timeStampBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          timeStamp_ != null &&
          timeStamp_ != org.ds.paxos.TimeStampProto.getDefaultInstance()) {
          getTimeStampBuilder().mergeFrom(value);
        } else {
          timeStamp_ = value;
        }
      } else {
        timeStampBuilder_.mergeFrom(value);
      }
      if (timeStamp_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 3;</code>
     */
    public Builder clearTimeStamp() {
      bitField0_ = (bitField0_ & ~0x00000004);
      timeStamp_ = null;
      if (timeStampBuilder_ != null) {
        timeStampBuilder_.dispose();
        timeStampBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 3;</code>
     */
    public org.ds.paxos.TimeStampProto.Builder getTimeStampBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getTimeStampFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 3;</code>
     */
    public org.ds.paxos.TimeStampProtoOrBuilder getTimeStampOrBuilder() {
      if (timeStampBuilder_ != null) {
        return timeStampBuilder_.getMessageOrBuilder();
      } else {
        return timeStamp_ == null ?
            org.ds.paxos.TimeStampProto.getDefaultInstance() : timeStamp_;
      }
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.ds.paxos.TimeStampProto, org.ds.paxos.TimeStampProto.Builder, org.ds.paxos.TimeStampProtoOrBuilder> 
        getTimeStampFieldBuilder() {
      if (timeStampBuilder_ == null) {
        timeStampBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.ds.paxos.TimeStampProto, org.ds.paxos.TimeStampProto.Builder, org.ds.paxos.TimeStampProtoOrBuilder>(
                getTimeStamp(),
                getParentForChildren(),
                isClean());
        timeStamp_ = null;
      }
      return timeStampBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:org.ds.paxos.ClientMessage)
  }

  // @@protoc_insertion_point(class_scope:org.ds.paxos.ClientMessage)
  private static final org.ds.paxos.ClientMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.ds.paxos.ClientMessage();
  }

  public static org.ds.paxos.ClientMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClientMessage>
      PARSER = new com.google.protobuf.AbstractParser<ClientMessage>() {
    @java.lang.Override
    public ClientMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ClientMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClientMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.ds.paxos.ClientMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

