// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/Raft.proto
// Protobuf Java Version: 4.29.3

package org.ds.paxos;

public interface ClientMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.ds.paxos.ClientMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.ds.paxos.Transaction t = 1;</code>
   * @return Whether the t field is set.
   */
  boolean hasT();
  /**
   * <code>.org.ds.paxos.Transaction t = 1;</code>
   * @return The t.
   */
  org.ds.paxos.Transaction getT();
  /**
   * <code>.org.ds.paxos.Transaction t = 1;</code>
   */
  org.ds.paxos.TransactionOrBuilder getTOrBuilder();

  /**
   * <code>int32 writeConcern = 2;</code>
   * @return The writeConcern.
   */
  int getWriteConcern();

  /**
   * <code>.org.ds.paxos.TimeStampProto timeStamp = 3;</code>
   * @return Whether the timeStamp field is set.
   */
  boolean hasTimeStamp();
  /**
   * <code>.org.ds.paxos.TimeStampProto timeStamp = 3;</code>
   * @return The timeStamp.
   */
  org.ds.paxos.TimeStampProto getTimeStamp();
  /**
   * <code>.org.ds.paxos.TimeStampProto timeStamp = 3;</code>
   */
  org.ds.paxos.TimeStampProtoOrBuilder getTimeStampOrBuilder();
}
