// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/Raft.proto
// Protobuf Java Version: 4.29.3

package org.ds.paxos;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.ds.paxos.Empty)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 data = 1;</code>
   * @return The data.
   */
  int getData();
}
