// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/Raft.proto
// Protobuf Java Version: 4.29.3

package org.ds.paxos;

/**
 * Protobuf type {@code org.ds.paxos.Log}
 */
public final class Log extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:org.ds.paxos.Log)
    LogOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Log.class.getName());
  }
  // Use Log.newBuilder() to construct.
  private Log(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Log() {
    log_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_Log_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_Log_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.ds.paxos.Log.class, org.ds.paxos.Log.Builder.class);
  }

  public static final int LOG_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<org.ds.paxos.LogEntryProto> log_;
  /**
   * <code>repeated .org.ds.paxos.LogEntryProto log = 1;</code>
   */
  @java.lang.Override
  public java.util.List<org.ds.paxos.LogEntryProto> getLogList() {
    return log_;
  }
  /**
   * <code>repeated .org.ds.paxos.LogEntryProto log = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.ds.paxos.LogEntryProtoOrBuilder> 
      getLogOrBuilderList() {
    return log_;
  }
  /**
   * <code>repeated .org.ds.paxos.LogEntryProto log = 1;</code>
   */
  @java.lang.Override
  public int getLogCount() {
    return log_.size();
  }
  /**
   * <code>repeated .org.ds.paxos.LogEntryProto log = 1;</code>
   */
  @java.lang.Override
  public org.ds.paxos.LogEntryProto getLog(int index) {
    return log_.get(index);
  }
  /**
   * <code>repeated .org.ds.paxos.LogEntryProto log = 1;</code>
   */
  @java.lang.Override
  public org.ds.paxos.LogEntryProtoOrBuilder getLogOrBuilder(
      int index) {
    return log_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < log_.size(); i++) {
      output.writeMessage(1, log_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < log_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, log_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.ds.paxos.Log)) {
      return super.equals(obj);
    }
    org.ds.paxos.Log other = (org.ds.paxos.Log) obj;

    if (!getLogList()
        .equals(other.getLogList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getLogCount() > 0) {
      hash = (37 * hash) + LOG_FIELD_NUMBER;
      hash = (53 * hash) + getLogList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.ds.paxos.Log parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.Log parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.Log parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.Log parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.Log parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.Log parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.Log parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.ds.paxos.Log parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.ds.paxos.Log parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.ds.paxos.Log parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.ds.paxos.Log parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.ds.paxos.Log parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.ds.paxos.Log prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.ds.paxos.Log}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.ds.paxos.Log)
      org.ds.paxos.LogOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_Log_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_Log_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.ds.paxos.Log.class, org.ds.paxos.Log.Builder.class);
    }

    // Construct using org.ds.paxos.Log.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (logBuilder_ == null) {
        log_ = java.util.Collections.emptyList();
      } else {
        log_ = null;
        logBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_Log_descriptor;
    }

    @java.lang.Override
    public org.ds.paxos.Log getDefaultInstanceForType() {
      return org.ds.paxos.Log.getDefaultInstance();
    }

    @java.lang.Override
    public org.ds.paxos.Log build() {
      org.ds.paxos.Log result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.ds.paxos.Log buildPartial() {
      org.ds.paxos.Log result = new org.ds.paxos.Log(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.ds.paxos.Log result) {
      if (logBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          log_ = java.util.Collections.unmodifiableList(log_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.log_ = log_;
      } else {
        result.log_ = logBuilder_.build();
      }
    }

    private void buildPartial0(org.ds.paxos.Log result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.ds.paxos.Log) {
        return mergeFrom((org.ds.paxos.Log)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.ds.paxos.Log other) {
      if (other == org.ds.paxos.Log.getDefaultInstance()) return this;
      if (logBuilder_ == null) {
        if (!other.log_.isEmpty()) {
          if (log_.isEmpty()) {
            log_ = other.log_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureLogIsMutable();
            log_.addAll(other.log_);
          }
          onChanged();
        }
      } else {
        if (!other.log_.isEmpty()) {
          if (logBuilder_.isEmpty()) {
            logBuilder_.dispose();
            logBuilder_ = null;
            log_ = other.log_;
            bitField0_ = (bitField0_ & ~0x00000001);
            logBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getLogFieldBuilder() : null;
          } else {
            logBuilder_.addAllMessages(other.log_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.ds.paxos.LogEntryProto m =
                  input.readMessage(
                      org.ds.paxos.LogEntryProto.parser(),
                      extensionRegistry);
              if (logBuilder_ == null) {
                ensureLogIsMutable();
                log_.add(m);
              } else {
                logBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<org.ds.paxos.LogEntryProto> log_ =
      java.util.Collections.emptyList();
    private void ensureLogIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        log_ = new java.util.ArrayList<org.ds.paxos.LogEntryProto>(log_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        org.ds.paxos.LogEntryProto, org.ds.paxos.LogEntryProto.Builder, org.ds.paxos.LogEntryProtoOrBuilder> logBuilder_;

    /**
     * <code>repeated .org.ds.paxos.LogEntryProto log = 1;</code>
     */
    public java.util.List<org.ds.paxos.LogEntryProto> getLogList() {
      if (logBuilder_ == null) {
        return java.util.Collections.unmodifiableList(log_);
      } else {
        return logBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .org.ds.paxos.LogEntryProto log = 1;</code>
     */
    public int getLogCount() {
      if (logBuilder_ == null) {
        return log_.size();
      } else {
        return logBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .org.ds.paxos.LogEntryProto log = 1;</code>
     */
    public org.ds.paxos.LogEntryProto getLog(int index) {
      if (logBuilder_ == null) {
        return log_.get(index);
      } else {
        return logBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .org.ds.paxos.LogEntryProto log = 1;</code>
     */
    public Builder setLog(
        int index, org.ds.paxos.LogEntryProto value) {
      if (logBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLogIsMutable();
        log_.set(index, value);
        onChanged();
      } else {
        logBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.ds.paxos.LogEntryProto log = 1;</code>
     */
    public Builder setLog(
        int index, org.ds.paxos.LogEntryProto.Builder builderForValue) {
      if (logBuilder_ == null) {
        ensureLogIsMutable();
        log_.set(index, builderForValue.build());
        onChanged();
      } else {
        logBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.ds.paxos.LogEntryProto log = 1;</code>
     */
    public Builder addLog(org.ds.paxos.LogEntryProto value) {
      if (logBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLogIsMutable();
        log_.add(value);
        onChanged();
      } else {
        logBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .org.ds.paxos.LogEntryProto log = 1;</code>
     */
    public Builder addLog(
        int index, org.ds.paxos.LogEntryProto value) {
      if (logBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLogIsMutable();
        log_.add(index, value);
        onChanged();
      } else {
        logBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.ds.paxos.LogEntryProto log = 1;</code>
     */
    public Builder addLog(
        org.ds.paxos.LogEntryProto.Builder builderForValue) {
      if (logBuilder_ == null) {
        ensureLogIsMutable();
        log_.add(builderForValue.build());
        onChanged();
      } else {
        logBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.ds.paxos.LogEntryProto log = 1;</code>
     */
    public Builder addLog(
        int index, org.ds.paxos.LogEntryProto.Builder builderForValue) {
      if (logBuilder_ == null) {
        ensureLogIsMutable();
        log_.add(index, builderForValue.build());
        onChanged();
      } else {
        logBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.ds.paxos.LogEntryProto log = 1;</code>
     */
    public Builder addAllLog(
        java.lang.Iterable<? extends org.ds.paxos.LogEntryProto> values) {
      if (logBuilder_ == null) {
        ensureLogIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, log_);
        onChanged();
      } else {
        logBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .org.ds.paxos.LogEntryProto log = 1;</code>
     */
    public Builder clearLog() {
      if (logBuilder_ == null) {
        log_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        logBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .org.ds.paxos.LogEntryProto log = 1;</code>
     */
    public Builder removeLog(int index) {
      if (logBuilder_ == null) {
        ensureLogIsMutable();
        log_.remove(index);
        onChanged();
      } else {
        logBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .org.ds.paxos.LogEntryProto log = 1;</code>
     */
    public org.ds.paxos.LogEntryProto.Builder getLogBuilder(
        int index) {
      return getLogFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .org.ds.paxos.LogEntryProto log = 1;</code>
     */
    public org.ds.paxos.LogEntryProtoOrBuilder getLogOrBuilder(
        int index) {
      if (logBuilder_ == null) {
        return log_.get(index);  } else {
        return logBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .org.ds.paxos.LogEntryProto log = 1;</code>
     */
    public java.util.List<? extends org.ds.paxos.LogEntryProtoOrBuilder> 
         getLogOrBuilderList() {
      if (logBuilder_ != null) {
        return logBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(log_);
      }
    }
    /**
     * <code>repeated .org.ds.paxos.LogEntryProto log = 1;</code>
     */
    public org.ds.paxos.LogEntryProto.Builder addLogBuilder() {
      return getLogFieldBuilder().addBuilder(
          org.ds.paxos.LogEntryProto.getDefaultInstance());
    }
    /**
     * <code>repeated .org.ds.paxos.LogEntryProto log = 1;</code>
     */
    public org.ds.paxos.LogEntryProto.Builder addLogBuilder(
        int index) {
      return getLogFieldBuilder().addBuilder(
          index, org.ds.paxos.LogEntryProto.getDefaultInstance());
    }
    /**
     * <code>repeated .org.ds.paxos.LogEntryProto log = 1;</code>
     */
    public java.util.List<org.ds.paxos.LogEntryProto.Builder> 
         getLogBuilderList() {
      return getLogFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        org.ds.paxos.LogEntryProto, org.ds.paxos.LogEntryProto.Builder, org.ds.paxos.LogEntryProtoOrBuilder> 
        getLogFieldBuilder() {
      if (logBuilder_ == null) {
        logBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            org.ds.paxos.LogEntryProto, org.ds.paxos.LogEntryProto.Builder, org.ds.paxos.LogEntryProtoOrBuilder>(
                log_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        log_ = null;
      }
      return logBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:org.ds.paxos.Log)
  }

  // @@protoc_insertion_point(class_scope:org.ds.paxos.Log)
  private static final org.ds.paxos.Log DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.ds.paxos.Log();
  }

  public static org.ds.paxos.Log getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Log>
      PARSER = new com.google.protobuf.AbstractParser<Log>() {
    @java.lang.Override
    public Log parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Log> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Log> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.ds.paxos.Log getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

