// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/Raft.proto
// Protobuf Java Version: 4.29.3

package org.ds.paxos;

/**
 * Protobuf type {@code org.ds.paxos.LogEntryProto}
 */
public final class LogEntryProto extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:org.ds.paxos.LogEntryProto)
    LogEntryProtoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      LogEntryProto.class.getName());
  }
  // Use LogEntryProto.newBuilder() to construct.
  private LogEntryProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private LogEntryProto() {
    serversThatReplicatedThisEntry_ = emptyBooleanList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_LogEntryProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_LogEntryProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.ds.paxos.LogEntryProto.class, org.ds.paxos.LogEntryProto.Builder.class);
  }

  private int bitField0_;
  public static final int LOGINDEX_FIELD_NUMBER = 1;
  private int logIndex_ = 0;
  /**
   * <code>int32 logIndex = 1;</code>
   * @return The logIndex.
   */
  @java.lang.Override
  public int getLogIndex() {
    return logIndex_;
  }

  public static final int TERM_FIELD_NUMBER = 2;
  private int term_ = 0;
  /**
   * <code>int32 term = 2;</code>
   * @return The term.
   */
  @java.lang.Override
  public int getTerm() {
    return term_;
  }

  public static final int WRITECONCERN_FIELD_NUMBER = 3;
  private int writeConcern_ = 0;
  /**
   * <code>int32 writeConcern = 3;</code>
   * @return The writeConcern.
   */
  @java.lang.Override
  public int getWriteConcern() {
    return writeConcern_;
  }

  public static final int T_FIELD_NUMBER = 4;
  private org.ds.paxos.Transaction t_;
  /**
   * <code>.org.ds.paxos.Transaction t = 4;</code>
   * @return Whether the t field is set.
   */
  @java.lang.Override
  public boolean hasT() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.org.ds.paxos.Transaction t = 4;</code>
   * @return The t.
   */
  @java.lang.Override
  public org.ds.paxos.Transaction getT() {
    return t_ == null ? org.ds.paxos.Transaction.getDefaultInstance() : t_;
  }
  /**
   * <code>.org.ds.paxos.Transaction t = 4;</code>
   */
  @java.lang.Override
  public org.ds.paxos.TransactionOrBuilder getTOrBuilder() {
    return t_ == null ? org.ds.paxos.Transaction.getDefaultInstance() : t_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 5;
  private org.ds.paxos.TimeStampProto timeStamp_;
  /**
   * <code>.org.ds.paxos.TimeStampProto timeStamp = 5;</code>
   * @return Whether the timeStamp field is set.
   */
  @java.lang.Override
  public boolean hasTimeStamp() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.org.ds.paxos.TimeStampProto timeStamp = 5;</code>
   * @return The timeStamp.
   */
  @java.lang.Override
  public org.ds.paxos.TimeStampProto getTimeStamp() {
    return timeStamp_ == null ? org.ds.paxos.TimeStampProto.getDefaultInstance() : timeStamp_;
  }
  /**
   * <code>.org.ds.paxos.TimeStampProto timeStamp = 5;</code>
   */
  @java.lang.Override
  public org.ds.paxos.TimeStampProtoOrBuilder getTimeStampOrBuilder() {
    return timeStamp_ == null ? org.ds.paxos.TimeStampProto.getDefaultInstance() : timeStamp_;
  }

  public static final int SERVERSTHATREPLICATEDTHISENTRY_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.BooleanList serversThatReplicatedThisEntry_ =
      emptyBooleanList();
  /**
   * <code>repeated bool serversThatReplicatedThisEntry = 6;</code>
   * @return A list containing the serversThatReplicatedThisEntry.
   */
  @java.lang.Override
  public java.util.List<java.lang.Boolean>
      getServersThatReplicatedThisEntryList() {
    return serversThatReplicatedThisEntry_;
  }
  /**
   * <code>repeated bool serversThatReplicatedThisEntry = 6;</code>
   * @return The count of serversThatReplicatedThisEntry.
   */
  public int getServersThatReplicatedThisEntryCount() {
    return serversThatReplicatedThisEntry_.size();
  }
  /**
   * <code>repeated bool serversThatReplicatedThisEntry = 6;</code>
   * @param index The index of the element to return.
   * @return The serversThatReplicatedThisEntry at the given index.
   */
  public boolean getServersThatReplicatedThisEntry(int index) {
    return serversThatReplicatedThisEntry_.getBoolean(index);
  }
  private int serversThatReplicatedThisEntryMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (logIndex_ != 0) {
      output.writeInt32(1, logIndex_);
    }
    if (term_ != 0) {
      output.writeInt32(2, term_);
    }
    if (writeConcern_ != 0) {
      output.writeInt32(3, writeConcern_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(4, getT());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(5, getTimeStamp());
    }
    if (getServersThatReplicatedThisEntryList().size() > 0) {
      output.writeUInt32NoTag(50);
      output.writeUInt32NoTag(serversThatReplicatedThisEntryMemoizedSerializedSize);
    }
    for (int i = 0; i < serversThatReplicatedThisEntry_.size(); i++) {
      output.writeBoolNoTag(serversThatReplicatedThisEntry_.getBoolean(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (logIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, logIndex_);
    }
    if (term_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, term_);
    }
    if (writeConcern_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, writeConcern_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getT());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getTimeStamp());
    }
    {
      int dataSize = 0;
      dataSize = 1 * getServersThatReplicatedThisEntryList().size();
      size += dataSize;
      if (!getServersThatReplicatedThisEntryList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      serversThatReplicatedThisEntryMemoizedSerializedSize = dataSize;
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.ds.paxos.LogEntryProto)) {
      return super.equals(obj);
    }
    org.ds.paxos.LogEntryProto other = (org.ds.paxos.LogEntryProto) obj;

    if (getLogIndex()
        != other.getLogIndex()) return false;
    if (getTerm()
        != other.getTerm()) return false;
    if (getWriteConcern()
        != other.getWriteConcern()) return false;
    if (hasT() != other.hasT()) return false;
    if (hasT()) {
      if (!getT()
          .equals(other.getT())) return false;
    }
    if (hasTimeStamp() != other.hasTimeStamp()) return false;
    if (hasTimeStamp()) {
      if (!getTimeStamp()
          .equals(other.getTimeStamp())) return false;
    }
    if (!getServersThatReplicatedThisEntryList()
        .equals(other.getServersThatReplicatedThisEntryList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LOGINDEX_FIELD_NUMBER;
    hash = (53 * hash) + getLogIndex();
    hash = (37 * hash) + TERM_FIELD_NUMBER;
    hash = (53 * hash) + getTerm();
    hash = (37 * hash) + WRITECONCERN_FIELD_NUMBER;
    hash = (53 * hash) + getWriteConcern();
    if (hasT()) {
      hash = (37 * hash) + T_FIELD_NUMBER;
      hash = (53 * hash) + getT().hashCode();
    }
    if (hasTimeStamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimeStamp().hashCode();
    }
    if (getServersThatReplicatedThisEntryCount() > 0) {
      hash = (37 * hash) + SERVERSTHATREPLICATEDTHISENTRY_FIELD_NUMBER;
      hash = (53 * hash) + getServersThatReplicatedThisEntryList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.ds.paxos.LogEntryProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.LogEntryProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.LogEntryProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.LogEntryProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.LogEntryProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.LogEntryProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.LogEntryProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.ds.paxos.LogEntryProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.ds.paxos.LogEntryProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.ds.paxos.LogEntryProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.ds.paxos.LogEntryProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.ds.paxos.LogEntryProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.ds.paxos.LogEntryProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.ds.paxos.LogEntryProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.ds.paxos.LogEntryProto)
      org.ds.paxos.LogEntryProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_LogEntryProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_LogEntryProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.ds.paxos.LogEntryProto.class, org.ds.paxos.LogEntryProto.Builder.class);
    }

    // Construct using org.ds.paxos.LogEntryProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getTFieldBuilder();
        getTimeStampFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      logIndex_ = 0;
      term_ = 0;
      writeConcern_ = 0;
      t_ = null;
      if (tBuilder_ != null) {
        tBuilder_.dispose();
        tBuilder_ = null;
      }
      timeStamp_ = null;
      if (timeStampBuilder_ != null) {
        timeStampBuilder_.dispose();
        timeStampBuilder_ = null;
      }
      serversThatReplicatedThisEntry_ = emptyBooleanList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_LogEntryProto_descriptor;
    }

    @java.lang.Override
    public org.ds.paxos.LogEntryProto getDefaultInstanceForType() {
      return org.ds.paxos.LogEntryProto.getDefaultInstance();
    }

    @java.lang.Override
    public org.ds.paxos.LogEntryProto build() {
      org.ds.paxos.LogEntryProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.ds.paxos.LogEntryProto buildPartial() {
      org.ds.paxos.LogEntryProto result = new org.ds.paxos.LogEntryProto(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.ds.paxos.LogEntryProto result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.logIndex_ = logIndex_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.term_ = term_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.writeConcern_ = writeConcern_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.t_ = tBuilder_ == null
            ? t_
            : tBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.timeStamp_ = timeStampBuilder_ == null
            ? timeStamp_
            : timeStampBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        serversThatReplicatedThisEntry_.makeImmutable();
        result.serversThatReplicatedThisEntry_ = serversThatReplicatedThisEntry_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.ds.paxos.LogEntryProto) {
        return mergeFrom((org.ds.paxos.LogEntryProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.ds.paxos.LogEntryProto other) {
      if (other == org.ds.paxos.LogEntryProto.getDefaultInstance()) return this;
      if (other.getLogIndex() != 0) {
        setLogIndex(other.getLogIndex());
      }
      if (other.getTerm() != 0) {
        setTerm(other.getTerm());
      }
      if (other.getWriteConcern() != 0) {
        setWriteConcern(other.getWriteConcern());
      }
      if (other.hasT()) {
        mergeT(other.getT());
      }
      if (other.hasTimeStamp()) {
        mergeTimeStamp(other.getTimeStamp());
      }
      if (!other.serversThatReplicatedThisEntry_.isEmpty()) {
        if (serversThatReplicatedThisEntry_.isEmpty()) {
          serversThatReplicatedThisEntry_ = other.serversThatReplicatedThisEntry_;
          serversThatReplicatedThisEntry_.makeImmutable();
          bitField0_ |= 0x00000020;
        } else {
          ensureServersThatReplicatedThisEntryIsMutable();
          serversThatReplicatedThisEntry_.addAll(other.serversThatReplicatedThisEntry_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              logIndex_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              term_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              writeConcern_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              input.readMessage(
                  getTFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getTimeStampFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              boolean v = input.readBool();
              ensureServersThatReplicatedThisEntryIsMutable();
              serversThatReplicatedThisEntry_.addBoolean(v);
              break;
            } // case 48
            case 50: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              int alloc = length > 4096 ? 4096 : length;
              ensureServersThatReplicatedThisEntryIsMutable(alloc / 1);
              while (input.getBytesUntilLimit() > 0) {
                serversThatReplicatedThisEntry_.addBoolean(input.readBool());
              }
              input.popLimit(limit);
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int logIndex_ ;
    /**
     * <code>int32 logIndex = 1;</code>
     * @return The logIndex.
     */
    @java.lang.Override
    public int getLogIndex() {
      return logIndex_;
    }
    /**
     * <code>int32 logIndex = 1;</code>
     * @param value The logIndex to set.
     * @return This builder for chaining.
     */
    public Builder setLogIndex(int value) {

      logIndex_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 logIndex = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLogIndex() {
      bitField0_ = (bitField0_ & ~0x00000001);
      logIndex_ = 0;
      onChanged();
      return this;
    }

    private int term_ ;
    /**
     * <code>int32 term = 2;</code>
     * @return The term.
     */
    @java.lang.Override
    public int getTerm() {
      return term_;
    }
    /**
     * <code>int32 term = 2;</code>
     * @param value The term to set.
     * @return This builder for chaining.
     */
    public Builder setTerm(int value) {

      term_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 term = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTerm() {
      bitField0_ = (bitField0_ & ~0x00000002);
      term_ = 0;
      onChanged();
      return this;
    }

    private int writeConcern_ ;
    /**
     * <code>int32 writeConcern = 3;</code>
     * @return The writeConcern.
     */
    @java.lang.Override
    public int getWriteConcern() {
      return writeConcern_;
    }
    /**
     * <code>int32 writeConcern = 3;</code>
     * @param value The writeConcern to set.
     * @return This builder for chaining.
     */
    public Builder setWriteConcern(int value) {

      writeConcern_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 writeConcern = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearWriteConcern() {
      bitField0_ = (bitField0_ & ~0x00000004);
      writeConcern_ = 0;
      onChanged();
      return this;
    }

    private org.ds.paxos.Transaction t_;
    private com.google.protobuf.SingleFieldBuilder<
        org.ds.paxos.Transaction, org.ds.paxos.Transaction.Builder, org.ds.paxos.TransactionOrBuilder> tBuilder_;
    /**
     * <code>.org.ds.paxos.Transaction t = 4;</code>
     * @return Whether the t field is set.
     */
    public boolean hasT() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.org.ds.paxos.Transaction t = 4;</code>
     * @return The t.
     */
    public org.ds.paxos.Transaction getT() {
      if (tBuilder_ == null) {
        return t_ == null ? org.ds.paxos.Transaction.getDefaultInstance() : t_;
      } else {
        return tBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.ds.paxos.Transaction t = 4;</code>
     */
    public Builder setT(org.ds.paxos.Transaction value) {
      if (tBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        t_ = value;
      } else {
        tBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.org.ds.paxos.Transaction t = 4;</code>
     */
    public Builder setT(
        org.ds.paxos.Transaction.Builder builderForValue) {
      if (tBuilder_ == null) {
        t_ = builderForValue.build();
      } else {
        tBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.org.ds.paxos.Transaction t = 4;</code>
     */
    public Builder mergeT(org.ds.paxos.Transaction value) {
      if (tBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          t_ != null &&
          t_ != org.ds.paxos.Transaction.getDefaultInstance()) {
          getTBuilder().mergeFrom(value);
        } else {
          t_ = value;
        }
      } else {
        tBuilder_.mergeFrom(value);
      }
      if (t_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.org.ds.paxos.Transaction t = 4;</code>
     */
    public Builder clearT() {
      bitField0_ = (bitField0_ & ~0x00000008);
      t_ = null;
      if (tBuilder_ != null) {
        tBuilder_.dispose();
        tBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.org.ds.paxos.Transaction t = 4;</code>
     */
    public org.ds.paxos.Transaction.Builder getTBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getTFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.ds.paxos.Transaction t = 4;</code>
     */
    public org.ds.paxos.TransactionOrBuilder getTOrBuilder() {
      if (tBuilder_ != null) {
        return tBuilder_.getMessageOrBuilder();
      } else {
        return t_ == null ?
            org.ds.paxos.Transaction.getDefaultInstance() : t_;
      }
    }
    /**
     * <code>.org.ds.paxos.Transaction t = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.ds.paxos.Transaction, org.ds.paxos.Transaction.Builder, org.ds.paxos.TransactionOrBuilder> 
        getTFieldBuilder() {
      if (tBuilder_ == null) {
        tBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.ds.paxos.Transaction, org.ds.paxos.Transaction.Builder, org.ds.paxos.TransactionOrBuilder>(
                getT(),
                getParentForChildren(),
                isClean());
        t_ = null;
      }
      return tBuilder_;
    }

    private org.ds.paxos.TimeStampProto timeStamp_;
    private com.google.protobuf.SingleFieldBuilder<
        org.ds.paxos.TimeStampProto, org.ds.paxos.TimeStampProto.Builder, org.ds.paxos.TimeStampProtoOrBuilder> timeStampBuilder_;
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 5;</code>
     * @return Whether the timeStamp field is set.
     */
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 5;</code>
     * @return The timeStamp.
     */
    public org.ds.paxos.TimeStampProto getTimeStamp() {
      if (timeStampBuilder_ == null) {
        return timeStamp_ == null ? org.ds.paxos.TimeStampProto.getDefaultInstance() : timeStamp_;
      } else {
        return timeStampBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 5;</code>
     */
    public Builder setTimeStamp(org.ds.paxos.TimeStampProto value) {
      if (timeStampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timeStamp_ = value;
      } else {
        timeStampBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 5;</code>
     */
    public Builder setTimeStamp(
        org.ds.paxos.TimeStampProto.Builder builderForValue) {
      if (timeStampBuilder_ == null) {
        timeStamp_ = builderForValue.build();
      } else {
        timeStampBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 5;</code>
     */
    public Builder mergeTimeStamp(org.ds.paxos.TimeStampProto value) {
      if (timeStampBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          timeStamp_ != null &&
          timeStamp_ != org.ds.paxos.TimeStampProto.getDefaultInstance()) {
          getTimeStampBuilder().mergeFrom(value);
        } else {
          timeStamp_ = value;
        }
      } else {
        timeStampBuilder_.mergeFrom(value);
      }
      if (timeStamp_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 5;</code>
     */
    public Builder clearTimeStamp() {
      bitField0_ = (bitField0_ & ~0x00000010);
      timeStamp_ = null;
      if (timeStampBuilder_ != null) {
        timeStampBuilder_.dispose();
        timeStampBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 5;</code>
     */
    public org.ds.paxos.TimeStampProto.Builder getTimeStampBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getTimeStampFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 5;</code>
     */
    public org.ds.paxos.TimeStampProtoOrBuilder getTimeStampOrBuilder() {
      if (timeStampBuilder_ != null) {
        return timeStampBuilder_.getMessageOrBuilder();
      } else {
        return timeStamp_ == null ?
            org.ds.paxos.TimeStampProto.getDefaultInstance() : timeStamp_;
      }
    }
    /**
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.ds.paxos.TimeStampProto, org.ds.paxos.TimeStampProto.Builder, org.ds.paxos.TimeStampProtoOrBuilder> 
        getTimeStampFieldBuilder() {
      if (timeStampBuilder_ == null) {
        timeStampBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.ds.paxos.TimeStampProto, org.ds.paxos.TimeStampProto.Builder, org.ds.paxos.TimeStampProtoOrBuilder>(
                getTimeStamp(),
                getParentForChildren(),
                isClean());
        timeStamp_ = null;
      }
      return timeStampBuilder_;
    }

    private com.google.protobuf.Internal.BooleanList serversThatReplicatedThisEntry_ = emptyBooleanList();
    private void ensureServersThatReplicatedThisEntryIsMutable() {
      if (!serversThatReplicatedThisEntry_.isModifiable()) {
        serversThatReplicatedThisEntry_ = makeMutableCopy(serversThatReplicatedThisEntry_);
      }
      bitField0_ |= 0x00000020;
    }
    private void ensureServersThatReplicatedThisEntryIsMutable(int capacity) {
      if (!serversThatReplicatedThisEntry_.isModifiable()) {
        serversThatReplicatedThisEntry_ = makeMutableCopy(serversThatReplicatedThisEntry_, capacity);
      }
      bitField0_ |= 0x00000020;
    }
    /**
     * <code>repeated bool serversThatReplicatedThisEntry = 6;</code>
     * @return A list containing the serversThatReplicatedThisEntry.
     */
    public java.util.List<java.lang.Boolean>
        getServersThatReplicatedThisEntryList() {
      serversThatReplicatedThisEntry_.makeImmutable();
      return serversThatReplicatedThisEntry_;
    }
    /**
     * <code>repeated bool serversThatReplicatedThisEntry = 6;</code>
     * @return The count of serversThatReplicatedThisEntry.
     */
    public int getServersThatReplicatedThisEntryCount() {
      return serversThatReplicatedThisEntry_.size();
    }
    /**
     * <code>repeated bool serversThatReplicatedThisEntry = 6;</code>
     * @param index The index of the element to return.
     * @return The serversThatReplicatedThisEntry at the given index.
     */
    public boolean getServersThatReplicatedThisEntry(int index) {
      return serversThatReplicatedThisEntry_.getBoolean(index);
    }
    /**
     * <code>repeated bool serversThatReplicatedThisEntry = 6;</code>
     * @param index The index to set the value at.
     * @param value The serversThatReplicatedThisEntry to set.
     * @return This builder for chaining.
     */
    public Builder setServersThatReplicatedThisEntry(
        int index, boolean value) {

      ensureServersThatReplicatedThisEntryIsMutable();
      serversThatReplicatedThisEntry_.setBoolean(index, value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated bool serversThatReplicatedThisEntry = 6;</code>
     * @param value The serversThatReplicatedThisEntry to add.
     * @return This builder for chaining.
     */
    public Builder addServersThatReplicatedThisEntry(boolean value) {

      ensureServersThatReplicatedThisEntryIsMutable();
      serversThatReplicatedThisEntry_.addBoolean(value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated bool serversThatReplicatedThisEntry = 6;</code>
     * @param values The serversThatReplicatedThisEntry to add.
     * @return This builder for chaining.
     */
    public Builder addAllServersThatReplicatedThisEntry(
        java.lang.Iterable<? extends java.lang.Boolean> values) {
      ensureServersThatReplicatedThisEntryIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, serversThatReplicatedThisEntry_);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated bool serversThatReplicatedThisEntry = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearServersThatReplicatedThisEntry() {
      serversThatReplicatedThisEntry_ = emptyBooleanList();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:org.ds.paxos.LogEntryProto)
  }

  // @@protoc_insertion_point(class_scope:org.ds.paxos.LogEntryProto)
  private static final org.ds.paxos.LogEntryProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.ds.paxos.LogEntryProto();
  }

  public static org.ds.paxos.LogEntryProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LogEntryProto>
      PARSER = new com.google.protobuf.AbstractParser<LogEntryProto>() {
    @java.lang.Override
    public LogEntryProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LogEntryProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LogEntryProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.ds.paxos.LogEntryProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

