// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/Raft.proto
// Protobuf Java Version: 4.29.3

package org.ds.paxos;

public interface LogEntryProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.ds.paxos.LogEntryProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 logIndex = 1;</code>
   * @return The logIndex.
   */
  int getLogIndex();

  /**
   * <code>int32 term = 2;</code>
   * @return The term.
   */
  int getTerm();

  /**
   * <code>int32 writeConcern = 3;</code>
   * @return The writeConcern.
   */
  int getWriteConcern();

  /**
   * <code>.org.ds.paxos.Transaction t = 4;</code>
   * @return Whether the t field is set.
   */
  boolean hasT();
  /**
   * <code>.org.ds.paxos.Transaction t = 4;</code>
   * @return The t.
   */
  org.ds.paxos.Transaction getT();
  /**
   * <code>.org.ds.paxos.Transaction t = 4;</code>
   */
  org.ds.paxos.TransactionOrBuilder getTOrBuilder();

  /**
   * <code>.org.ds.paxos.TimeStampProto timeStamp = 5;</code>
   * @return Whether the timeStamp field is set.
   */
  boolean hasTimeStamp();
  /**
   * <code>.org.ds.paxos.TimeStampProto timeStamp = 5;</code>
   * @return The timeStamp.
   */
  org.ds.paxos.TimeStampProto getTimeStamp();
  /**
   * <code>.org.ds.paxos.TimeStampProto timeStamp = 5;</code>
   */
  org.ds.paxos.TimeStampProtoOrBuilder getTimeStampOrBuilder();

  /**
   * <code>repeated bool serversThatReplicatedThisEntry = 6;</code>
   * @return A list containing the serversThatReplicatedThisEntry.
   */
  java.util.List<java.lang.Boolean> getServersThatReplicatedThisEntryList();
  /**
   * <code>repeated bool serversThatReplicatedThisEntry = 6;</code>
   * @return The count of serversThatReplicatedThisEntry.
   */
  int getServersThatReplicatedThisEntryCount();
  /**
   * <code>repeated bool serversThatReplicatedThisEntry = 6;</code>
   * @param index The index of the element to return.
   * @return The serversThatReplicatedThisEntry at the given index.
   */
  boolean getServersThatReplicatedThisEntry(int index);
}
