// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/Raft.proto
// Protobuf Java Version: 4.29.3

package org.ds.paxos;

public interface LogOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.ds.paxos.Log)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.ds.paxos.LogEntryProto log = 1;</code>
   */
  java.util.List<org.ds.paxos.LogEntryProto> 
      getLogList();
  /**
   * <code>repeated .org.ds.paxos.LogEntryProto log = 1;</code>
   */
  org.ds.paxos.LogEntryProto getLog(int index);
  /**
   * <code>repeated .org.ds.paxos.LogEntryProto log = 1;</code>
   */
  int getLogCount();
  /**
   * <code>repeated .org.ds.paxos.LogEntryProto log = 1;</code>
   */
  java.util.List<? extends org.ds.paxos.LogEntryProtoOrBuilder> 
      getLogOrBuilderList();
  /**
   * <code>repeated .org.ds.paxos.LogEntryProto log = 1;</code>
   */
  org.ds.paxos.LogEntryProtoOrBuilder getLogOrBuilder(
      int index);
}
