// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/Raft.proto
// Protobuf Java Version: 4.29.3

package org.ds.paxos;

public final class RaftOuterClass {
  private RaftOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      RaftOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_ds_paxos_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_ds_paxos_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_ds_paxos_Balance_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_ds_paxos_Balance_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_ds_paxos_ReadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_ds_paxos_ReadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_ds_paxos_AckMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_ds_paxos_AckMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_ds_paxos_Ack_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_ds_paxos_Ack_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_ds_paxos_ClientMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_ds_paxos_ClientMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_ds_paxos_Transaction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_ds_paxos_Transaction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_ds_paxos_LogEntryProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_ds_paxos_LogEntryProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_ds_paxos_TimeStampProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_ds_paxos_TimeStampProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_ds_paxos_Log_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_ds_paxos_Log_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_ds_paxos_AppendEntriesArgument_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_ds_paxos_AppendEntriesArgument_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_ds_paxos_RequestVoteArguments_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_ds_paxos_RequestVoteArguments_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_ds_paxos_AppendEntriesResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_ds_paxos_AppendEntriesResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_ds_paxos_RequestVoteResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_ds_paxos_RequestVoteResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_ds_paxos_TokenStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_ds_paxos_TokenStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_ds_paxos_TokenStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_ds_paxos_TokenStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_ds_paxos_TokenUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_ds_paxos_TokenUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_ds_paxos_TokenConsumeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_ds_paxos_TokenConsumeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_ds_paxos_TokenConsumeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_ds_paxos_TokenConsumeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035src/main/resources/Raft.proto\022\014org.ds." +
      "paxos\"\025\n\005Empty\022\014\n\004data\030\001 \001(\005\"<\n\007Balance\022" +
      "\017\n\007balance\030\001 \001(\001\022\017\n\007accName\030\002 \001(\t\022\017\n\007fai" +
      "lure\030\003 \001(\010\"\177\n\013ReadRequest\022.\n\013readConcern" +
      "\030\001 \001(\0162\031.org.ds.paxos.ReadConcern\022/\n\ttim" +
      "eStamp\030\002 \001(\0132\034.org.ds.paxos.TimeStampPro" +
      "to\022\017\n\007accName\030\003 \001(\t\"y\n\nAckMessage\022$\n\001t\030\001" +
      " \001(\0132\031.org.ds.paxos.Transaction\022.\n\010timSt" +
      "amp\030\002 \001(\0132\034.org.ds.paxos.TimeStampProto\022" +
      "\025\n\rcurrentLeader\030\003 \001(\005\"3\n\003Ack\022,\n\nackMess" +
      "age\030\001 \003(\0132\030.org.ds.paxos.AckMessage\"|\n\rC" +
      "lientMessage\022$\n\001t\030\001 \001(\0132\031.org.ds.paxos.T" +
      "ransaction\022\024\n\014writeConcern\030\002 \001(\005\022/\n\ttime" +
      "Stamp\030\003 \001(\0132\034.org.ds.paxos.TimeStampProt" +
      "o\"K\n\013Transaction\022\016\n\006sender\030\001 \001(\t\022\020\n\010rece" +
      "iver\030\002 \001(\t\022\016\n\006amount\030\003 \001(\001\022\n\n\002id\030\004 \001(\t\"\304" +
      "\001\n\rLogEntryProto\022\020\n\010logIndex\030\001 \001(\005\022\014\n\004te" +
      "rm\030\002 \001(\005\022\024\n\014writeConcern\030\003 \001(\005\022$\n\001t\030\004 \001(" +
      "\0132\031.org.ds.paxos.Transaction\022/\n\ttimeStam" +
      "p\030\005 \001(\0132\034.org.ds.paxos.TimeStampProto\022&\n" +
      "\036serversThatReplicatedThisEntry\030\006 \003(\010\"&\n" +
      "\016TimeStampProto\022\t\n\001p\030\001 \001(\003\022\t\n\001l\030\002 \001(\003\"/\n" +
      "\003Log\022(\n\003log\030\001 \003(\0132\033.org.ds.paxos.LogEntr" +
      "yProto\"\360\001\n\025AppendEntriesArgument\022\023\n\013lead" +
      "ersTerm\030\001 \001(\005\022\024\n\014prevLogIndex\030\002 \001(\005\022\021\n\tl" +
      "eadersId\030\003 \001(\005\022\023\n\013prevLogTerm\030\004 \001(\005\022*\n\017e" +
      "ntriesToAppend\030\005 \001(\0132\021.org.ds.paxos.Log\022" +
      "\025\n\rleadersCommit\030\006 \001(\005\022\020\n\010ackIndex\030\007 \001(\005" +
      "\022/\n\ttimeStamp\030\010 \001(\0132\034.org.ds.paxos.TimeS" +
      "tampProto\"n\n\024RequestVoteArguments\022\026\n\016can" +
      "didatesTerm\030\001 \001(\005\022\023\n\013candidateId\030\002 \001(\005\022\024" +
      "\n\014lastLogIndex\030\003 \001(\005\022\023\n\013lastLogTerm\030\004 \001(" +
      "\005\"\206\001\n\023AppendEntriesResult\022\023\n\013currentTerm" +
      "\030\001 \001(\005\022\025\n\risSuccessFull\030\002 \001(\010\022\022\n\nfollowe" +
      "rId\030\003 \001(\005\022/\n\ttimeStamp\030\004 \001(\0132\034.org.ds.pa" +
      "xos.TimeStampProto\"?\n\021RequestVoteResult\022" +
      "\023\n\013currentTerm\030\001 \001(\005\022\025\n\risVoteGranted\030\002 " +
      "\001(\010\"\024\n\022TokenStatusRequest\"G\n\023TokenStatus" +
      "Response\022\027\n\017tokensAvailable\030\001 \001(\001\022\027\n\017las" +
      "tUpdatedTime\030\002 \001(\003\"F\n\022TokenUpdateRequest" +
      "\022\027\n\017tokensRemaining\030\001 \001(\001\022\027\n\017lastUpdated" +
      "Time\030\002 \001(\003\"-\n\023TokenConsumeRequest\022\026\n\016req" +
      "uiredTokens\030\001 \001(\001\"Y\n\024TokenConsumeRespons" +
      "e\022\017\n\007granted\030\001 \001(\010\022\027\n\017tokensRemaining\030\002 " +
      "\001(\001\022\027\n\017lastUpdatedTime\030\003 \001(\003*8\n\013ReadConc" +
      "ern\022\020\n\014LINEARIZABLE\020\000\022\t\n\005LOCAL\020\001\022\014\n\010MAJO" +
      "RITY\020\0022\256\003\n\004Raft\022C\n\017SendTransaction\022\033.org" +
      ".ds.paxos.ClientMessage\032\023.org.ds.paxos.E" +
      "mpty\022W\n\rAppendEntries\022#.org.ds.paxos.App" +
      "endEntriesArgument\032!.org.ds.paxos.Append" +
      "EntriesResult\022R\n\013RequestVote\022\".org.ds.pa" +
      "xos.RequestVoteArguments\032\037.org.ds.paxos." +
      "RequestVoteResult\0224\n\010printLog\022\023.org.ds.p" +
      "axos.Empty\032\023.org.ds.paxos.Empty\0229\n\017sendA" +
      "ckToClient\022\021.org.ds.paxos.Ack\032\023.org.ds.p" +
      "axos.Empty\022C\n\017sendReadRequest\022\031.org.ds.p" +
      "axos.ReadRequest\032\025.org.ds.paxos.Balance2" +
      "\207\002\n\013TokenBucket\022U\n\016GetTokenStatus\022 .org." +
      "ds.paxos.TokenStatusRequest\032!.org.ds.pax" +
      "os.TokenStatusResponse\022I\n\020UpdateTokenSta" +
      "te\022 .org.ds.paxos.TokenUpdateRequest\032\023.o" +
      "rg.ds.paxos.Empty\022V\n\rConsumeTokens\022!.org" +
      ".ds.paxos.TokenConsumeRequest\032\".org.ds.p" +
      "axos.TokenConsumeResponseB\020\n\014org.ds.paxo" +
      "sP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_ds_paxos_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_ds_paxos_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_ds_paxos_Empty_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_org_ds_paxos_Balance_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_ds_paxos_Balance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_ds_paxos_Balance_descriptor,
        new java.lang.String[] { "Balance", "AccName", "Failure", });
    internal_static_org_ds_paxos_ReadRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_ds_paxos_ReadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_ds_paxos_ReadRequest_descriptor,
        new java.lang.String[] { "ReadConcern", "TimeStamp", "AccName", });
    internal_static_org_ds_paxos_AckMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_ds_paxos_AckMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_ds_paxos_AckMessage_descriptor,
        new java.lang.String[] { "T", "TimStamp", "CurrentLeader", });
    internal_static_org_ds_paxos_Ack_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_org_ds_paxos_Ack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_ds_paxos_Ack_descriptor,
        new java.lang.String[] { "AckMessage", });
    internal_static_org_ds_paxos_ClientMessage_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_org_ds_paxos_ClientMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_ds_paxos_ClientMessage_descriptor,
        new java.lang.String[] { "T", "WriteConcern", "TimeStamp", });
    internal_static_org_ds_paxos_Transaction_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_org_ds_paxos_Transaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_ds_paxos_Transaction_descriptor,
        new java.lang.String[] { "Sender", "Receiver", "Amount", "Id", });
    internal_static_org_ds_paxos_LogEntryProto_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_org_ds_paxos_LogEntryProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_ds_paxos_LogEntryProto_descriptor,
        new java.lang.String[] { "LogIndex", "Term", "WriteConcern", "T", "TimeStamp", "ServersThatReplicatedThisEntry", });
    internal_static_org_ds_paxos_TimeStampProto_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_org_ds_paxos_TimeStampProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_ds_paxos_TimeStampProto_descriptor,
        new java.lang.String[] { "P", "L", });
    internal_static_org_ds_paxos_Log_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_org_ds_paxos_Log_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_ds_paxos_Log_descriptor,
        new java.lang.String[] { "Log", });
    internal_static_org_ds_paxos_AppendEntriesArgument_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_org_ds_paxos_AppendEntriesArgument_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_ds_paxos_AppendEntriesArgument_descriptor,
        new java.lang.String[] { "LeadersTerm", "PrevLogIndex", "LeadersId", "PrevLogTerm", "EntriesToAppend", "LeadersCommit", "AckIndex", "TimeStamp", });
    internal_static_org_ds_paxos_RequestVoteArguments_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_org_ds_paxos_RequestVoteArguments_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_ds_paxos_RequestVoteArguments_descriptor,
        new java.lang.String[] { "CandidatesTerm", "CandidateId", "LastLogIndex", "LastLogTerm", });
    internal_static_org_ds_paxos_AppendEntriesResult_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_org_ds_paxos_AppendEntriesResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_ds_paxos_AppendEntriesResult_descriptor,
        new java.lang.String[] { "CurrentTerm", "IsSuccessFull", "FollowerId", "TimeStamp", });
    internal_static_org_ds_paxos_RequestVoteResult_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_org_ds_paxos_RequestVoteResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_ds_paxos_RequestVoteResult_descriptor,
        new java.lang.String[] { "CurrentTerm", "IsVoteGranted", });
    internal_static_org_ds_paxos_TokenStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_org_ds_paxos_TokenStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_ds_paxos_TokenStatusRequest_descriptor,
        new java.lang.String[] { });
    internal_static_org_ds_paxos_TokenStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_org_ds_paxos_TokenStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_ds_paxos_TokenStatusResponse_descriptor,
        new java.lang.String[] { "TokensAvailable", "LastUpdatedTime", });
    internal_static_org_ds_paxos_TokenUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_org_ds_paxos_TokenUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_ds_paxos_TokenUpdateRequest_descriptor,
        new java.lang.String[] { "TokensRemaining", "LastUpdatedTime", });
    internal_static_org_ds_paxos_TokenConsumeRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_org_ds_paxos_TokenConsumeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_ds_paxos_TokenConsumeRequest_descriptor,
        new java.lang.String[] { "RequiredTokens", });
    internal_static_org_ds_paxos_TokenConsumeResponse_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_org_ds_paxos_TokenConsumeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_ds_paxos_TokenConsumeResponse_descriptor,
        new java.lang.String[] { "Granted", "TokensRemaining", "LastUpdatedTime", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
