// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/Raft.proto
// Protobuf Java Version: 4.29.3

package org.ds.paxos;

/**
 * Protobuf enum {@code org.ds.paxos.ReadConcern}
 */
public enum ReadConcern
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>LINEARIZABLE = 0;</code>
   */
  LINEARIZABLE(0),
  /**
   * <code>LOCAL = 1;</code>
   */
  LOCAL(1),
  /**
   * <code>MAJORITY = 2;</code>
   */
  MAJORITY(2),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      ReadConcern.class.getName());
  }
  /**
   * <code>LINEARIZABLE = 0;</code>
   */
  public static final int LINEARIZABLE_VALUE = 0;
  /**
   * <code>LOCAL = 1;</code>
   */
  public static final int LOCAL_VALUE = 1;
  /**
   * <code>MAJORITY = 2;</code>
   */
  public static final int MAJORITY_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ReadConcern valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ReadConcern forNumber(int value) {
    switch (value) {
      case 0: return LINEARIZABLE;
      case 1: return LOCAL;
      case 2: return MAJORITY;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ReadConcern>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ReadConcern> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ReadConcern>() {
          public ReadConcern findValueByNumber(int number) {
            return ReadConcern.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.ds.paxos.RaftOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final ReadConcern[] VALUES = values();

  public static ReadConcern valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ReadConcern(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:org.ds.paxos.ReadConcern)
}

