// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/Raft.proto
// Protobuf Java Version: 4.29.3

package org.ds.paxos;

/**
 * Protobuf type {@code org.ds.paxos.ReadRequest}
 */
public final class ReadRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:org.ds.paxos.ReadRequest)
    ReadRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      ReadRequest.class.getName());
  }
  // Use ReadRequest.newBuilder() to construct.
  private ReadRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ReadRequest() {
    readConcern_ = 0;
    accName_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_ReadRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_ReadRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.ds.paxos.ReadRequest.class, org.ds.paxos.ReadRequest.Builder.class);
  }

  private int bitField0_;
  public static final int READCONCERN_FIELD_NUMBER = 1;
  private int readConcern_ = 0;
  /**
   * <code>.org.ds.paxos.ReadConcern readConcern = 1;</code>
   * @return The enum numeric value on the wire for readConcern.
   */
  @java.lang.Override public int getReadConcernValue() {
    return readConcern_;
  }
  /**
   * <code>.org.ds.paxos.ReadConcern readConcern = 1;</code>
   * @return The readConcern.
   */
  @java.lang.Override public org.ds.paxos.ReadConcern getReadConcern() {
    org.ds.paxos.ReadConcern result = org.ds.paxos.ReadConcern.forNumber(readConcern_);
    return result == null ? org.ds.paxos.ReadConcern.UNRECOGNIZED : result;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 2;
  private org.ds.paxos.TimeStampProto timeStamp_;
  /**
   * <pre>
   * for causal consistency
   * </pre>
   *
   * <code>.org.ds.paxos.TimeStampProto timeStamp = 2;</code>
   * @return Whether the timeStamp field is set.
   */
  @java.lang.Override
  public boolean hasTimeStamp() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * for causal consistency
   * </pre>
   *
   * <code>.org.ds.paxos.TimeStampProto timeStamp = 2;</code>
   * @return The timeStamp.
   */
  @java.lang.Override
  public org.ds.paxos.TimeStampProto getTimeStamp() {
    return timeStamp_ == null ? org.ds.paxos.TimeStampProto.getDefaultInstance() : timeStamp_;
  }
  /**
   * <pre>
   * for causal consistency
   * </pre>
   *
   * <code>.org.ds.paxos.TimeStampProto timeStamp = 2;</code>
   */
  @java.lang.Override
  public org.ds.paxos.TimeStampProtoOrBuilder getTimeStampOrBuilder() {
    return timeStamp_ == null ? org.ds.paxos.TimeStampProto.getDefaultInstance() : timeStamp_;
  }

  public static final int ACCNAME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object accName_ = "";
  /**
   * <code>string accName = 3;</code>
   * @return The accName.
   */
  @java.lang.Override
  public java.lang.String getAccName() {
    java.lang.Object ref = accName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      accName_ = s;
      return s;
    }
  }
  /**
   * <code>string accName = 3;</code>
   * @return The bytes for accName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAccNameBytes() {
    java.lang.Object ref = accName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (readConcern_ != org.ds.paxos.ReadConcern.LINEARIZABLE.getNumber()) {
      output.writeEnum(1, readConcern_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getTimeStamp());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(accName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, accName_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (readConcern_ != org.ds.paxos.ReadConcern.LINEARIZABLE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, readConcern_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getTimeStamp());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(accName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, accName_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.ds.paxos.ReadRequest)) {
      return super.equals(obj);
    }
    org.ds.paxos.ReadRequest other = (org.ds.paxos.ReadRequest) obj;

    if (readConcern_ != other.readConcern_) return false;
    if (hasTimeStamp() != other.hasTimeStamp()) return false;
    if (hasTimeStamp()) {
      if (!getTimeStamp()
          .equals(other.getTimeStamp())) return false;
    }
    if (!getAccName()
        .equals(other.getAccName())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + READCONCERN_FIELD_NUMBER;
    hash = (53 * hash) + readConcern_;
    if (hasTimeStamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimeStamp().hashCode();
    }
    hash = (37 * hash) + ACCNAME_FIELD_NUMBER;
    hash = (53 * hash) + getAccName().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.ds.paxos.ReadRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.ReadRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.ReadRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.ReadRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.ReadRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.ReadRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.ReadRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.ds.paxos.ReadRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.ds.paxos.ReadRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.ds.paxos.ReadRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.ds.paxos.ReadRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.ds.paxos.ReadRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.ds.paxos.ReadRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.ds.paxos.ReadRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.ds.paxos.ReadRequest)
      org.ds.paxos.ReadRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_ReadRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_ReadRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.ds.paxos.ReadRequest.class, org.ds.paxos.ReadRequest.Builder.class);
    }

    // Construct using org.ds.paxos.ReadRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getTimeStampFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      readConcern_ = 0;
      timeStamp_ = null;
      if (timeStampBuilder_ != null) {
        timeStampBuilder_.dispose();
        timeStampBuilder_ = null;
      }
      accName_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_ReadRequest_descriptor;
    }

    @java.lang.Override
    public org.ds.paxos.ReadRequest getDefaultInstanceForType() {
      return org.ds.paxos.ReadRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.ds.paxos.ReadRequest build() {
      org.ds.paxos.ReadRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.ds.paxos.ReadRequest buildPartial() {
      org.ds.paxos.ReadRequest result = new org.ds.paxos.ReadRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.ds.paxos.ReadRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.readConcern_ = readConcern_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.timeStamp_ = timeStampBuilder_ == null
            ? timeStamp_
            : timeStampBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.accName_ = accName_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.ds.paxos.ReadRequest) {
        return mergeFrom((org.ds.paxos.ReadRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.ds.paxos.ReadRequest other) {
      if (other == org.ds.paxos.ReadRequest.getDefaultInstance()) return this;
      if (other.readConcern_ != 0) {
        setReadConcernValue(other.getReadConcernValue());
      }
      if (other.hasTimeStamp()) {
        mergeTimeStamp(other.getTimeStamp());
      }
      if (!other.getAccName().isEmpty()) {
        accName_ = other.accName_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              readConcern_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getTimeStampFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              accName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int readConcern_ = 0;
    /**
     * <code>.org.ds.paxos.ReadConcern readConcern = 1;</code>
     * @return The enum numeric value on the wire for readConcern.
     */
    @java.lang.Override public int getReadConcernValue() {
      return readConcern_;
    }
    /**
     * <code>.org.ds.paxos.ReadConcern readConcern = 1;</code>
     * @param value The enum numeric value on the wire for readConcern to set.
     * @return This builder for chaining.
     */
    public Builder setReadConcernValue(int value) {
      readConcern_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.org.ds.paxos.ReadConcern readConcern = 1;</code>
     * @return The readConcern.
     */
    @java.lang.Override
    public org.ds.paxos.ReadConcern getReadConcern() {
      org.ds.paxos.ReadConcern result = org.ds.paxos.ReadConcern.forNumber(readConcern_);
      return result == null ? org.ds.paxos.ReadConcern.UNRECOGNIZED : result;
    }
    /**
     * <code>.org.ds.paxos.ReadConcern readConcern = 1;</code>
     * @param value The readConcern to set.
     * @return This builder for chaining.
     */
    public Builder setReadConcern(org.ds.paxos.ReadConcern value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      readConcern_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.org.ds.paxos.ReadConcern readConcern = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReadConcern() {
      bitField0_ = (bitField0_ & ~0x00000001);
      readConcern_ = 0;
      onChanged();
      return this;
    }

    private org.ds.paxos.TimeStampProto timeStamp_;
    private com.google.protobuf.SingleFieldBuilder<
        org.ds.paxos.TimeStampProto, org.ds.paxos.TimeStampProto.Builder, org.ds.paxos.TimeStampProtoOrBuilder> timeStampBuilder_;
    /**
     * <pre>
     * for causal consistency
     * </pre>
     *
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 2;</code>
     * @return Whether the timeStamp field is set.
     */
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * for causal consistency
     * </pre>
     *
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 2;</code>
     * @return The timeStamp.
     */
    public org.ds.paxos.TimeStampProto getTimeStamp() {
      if (timeStampBuilder_ == null) {
        return timeStamp_ == null ? org.ds.paxos.TimeStampProto.getDefaultInstance() : timeStamp_;
      } else {
        return timeStampBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * for causal consistency
     * </pre>
     *
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 2;</code>
     */
    public Builder setTimeStamp(org.ds.paxos.TimeStampProto value) {
      if (timeStampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timeStamp_ = value;
      } else {
        timeStampBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * for causal consistency
     * </pre>
     *
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 2;</code>
     */
    public Builder setTimeStamp(
        org.ds.paxos.TimeStampProto.Builder builderForValue) {
      if (timeStampBuilder_ == null) {
        timeStamp_ = builderForValue.build();
      } else {
        timeStampBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * for causal consistency
     * </pre>
     *
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 2;</code>
     */
    public Builder mergeTimeStamp(org.ds.paxos.TimeStampProto value) {
      if (timeStampBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          timeStamp_ != null &&
          timeStamp_ != org.ds.paxos.TimeStampProto.getDefaultInstance()) {
          getTimeStampBuilder().mergeFrom(value);
        } else {
          timeStamp_ = value;
        }
      } else {
        timeStampBuilder_.mergeFrom(value);
      }
      if (timeStamp_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * for causal consistency
     * </pre>
     *
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 2;</code>
     */
    public Builder clearTimeStamp() {
      bitField0_ = (bitField0_ & ~0x00000002);
      timeStamp_ = null;
      if (timeStampBuilder_ != null) {
        timeStampBuilder_.dispose();
        timeStampBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * for causal consistency
     * </pre>
     *
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 2;</code>
     */
    public org.ds.paxos.TimeStampProto.Builder getTimeStampBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getTimeStampFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * for causal consistency
     * </pre>
     *
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 2;</code>
     */
    public org.ds.paxos.TimeStampProtoOrBuilder getTimeStampOrBuilder() {
      if (timeStampBuilder_ != null) {
        return timeStampBuilder_.getMessageOrBuilder();
      } else {
        return timeStamp_ == null ?
            org.ds.paxos.TimeStampProto.getDefaultInstance() : timeStamp_;
      }
    }
    /**
     * <pre>
     * for causal consistency
     * </pre>
     *
     * <code>.org.ds.paxos.TimeStampProto timeStamp = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.ds.paxos.TimeStampProto, org.ds.paxos.TimeStampProto.Builder, org.ds.paxos.TimeStampProtoOrBuilder> 
        getTimeStampFieldBuilder() {
      if (timeStampBuilder_ == null) {
        timeStampBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.ds.paxos.TimeStampProto, org.ds.paxos.TimeStampProto.Builder, org.ds.paxos.TimeStampProtoOrBuilder>(
                getTimeStamp(),
                getParentForChildren(),
                isClean());
        timeStamp_ = null;
      }
      return timeStampBuilder_;
    }

    private java.lang.Object accName_ = "";
    /**
     * <code>string accName = 3;</code>
     * @return The accName.
     */
    public java.lang.String getAccName() {
      java.lang.Object ref = accName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string accName = 3;</code>
     * @return The bytes for accName.
     */
    public com.google.protobuf.ByteString
        getAccNameBytes() {
      java.lang.Object ref = accName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string accName = 3;</code>
     * @param value The accName to set.
     * @return This builder for chaining.
     */
    public Builder setAccName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      accName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string accName = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccName() {
      accName_ = getDefaultInstance().getAccName();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string accName = 3;</code>
     * @param value The bytes for accName to set.
     * @return This builder for chaining.
     */
    public Builder setAccNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      accName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:org.ds.paxos.ReadRequest)
  }

  // @@protoc_insertion_point(class_scope:org.ds.paxos.ReadRequest)
  private static final org.ds.paxos.ReadRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.ds.paxos.ReadRequest();
  }

  public static org.ds.paxos.ReadRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReadRequest>
      PARSER = new com.google.protobuf.AbstractParser<ReadRequest>() {
    @java.lang.Override
    public ReadRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ReadRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReadRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.ds.paxos.ReadRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

