// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/Raft.proto
// Protobuf Java Version: 4.29.3

package org.ds.paxos;

public interface ReadRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.ds.paxos.ReadRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.ds.paxos.ReadConcern readConcern = 1;</code>
   * @return The enum numeric value on the wire for readConcern.
   */
  int getReadConcernValue();
  /**
   * <code>.org.ds.paxos.ReadConcern readConcern = 1;</code>
   * @return The readConcern.
   */
  org.ds.paxos.ReadConcern getReadConcern();

  /**
   * <pre>
   * for causal consistency
   * </pre>
   *
   * <code>.org.ds.paxos.TimeStampProto timeStamp = 2;</code>
   * @return Whether the timeStamp field is set.
   */
  boolean hasTimeStamp();
  /**
   * <pre>
   * for causal consistency
   * </pre>
   *
   * <code>.org.ds.paxos.TimeStampProto timeStamp = 2;</code>
   * @return The timeStamp.
   */
  org.ds.paxos.TimeStampProto getTimeStamp();
  /**
   * <pre>
   * for causal consistency
   * </pre>
   *
   * <code>.org.ds.paxos.TimeStampProto timeStamp = 2;</code>
   */
  org.ds.paxos.TimeStampProtoOrBuilder getTimeStampOrBuilder();

  /**
   * <code>string accName = 3;</code>
   * @return The accName.
   */
  java.lang.String getAccName();
  /**
   * <code>string accName = 3;</code>
   * @return The bytes for accName.
   */
  com.google.protobuf.ByteString
      getAccNameBytes();
}
