// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/Raft.proto
// Protobuf Java Version: 4.29.3

package org.ds.paxos;

/**
 * Protobuf type {@code org.ds.paxos.RequestVoteArguments}
 */
public final class RequestVoteArguments extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:org.ds.paxos.RequestVoteArguments)
    RequestVoteArgumentsOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      RequestVoteArguments.class.getName());
  }
  // Use RequestVoteArguments.newBuilder() to construct.
  private RequestVoteArguments(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RequestVoteArguments() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_RequestVoteArguments_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_RequestVoteArguments_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.ds.paxos.RequestVoteArguments.class, org.ds.paxos.RequestVoteArguments.Builder.class);
  }

  public static final int CANDIDATESTERM_FIELD_NUMBER = 1;
  private int candidatesTerm_ = 0;
  /**
   * <code>int32 candidatesTerm = 1;</code>
   * @return The candidatesTerm.
   */
  @java.lang.Override
  public int getCandidatesTerm() {
    return candidatesTerm_;
  }

  public static final int CANDIDATEID_FIELD_NUMBER = 2;
  private int candidateId_ = 0;
  /**
   * <code>int32 candidateId = 2;</code>
   * @return The candidateId.
   */
  @java.lang.Override
  public int getCandidateId() {
    return candidateId_;
  }

  public static final int LASTLOGINDEX_FIELD_NUMBER = 3;
  private int lastLogIndex_ = 0;
  /**
   * <code>int32 lastLogIndex = 3;</code>
   * @return The lastLogIndex.
   */
  @java.lang.Override
  public int getLastLogIndex() {
    return lastLogIndex_;
  }

  public static final int LASTLOGTERM_FIELD_NUMBER = 4;
  private int lastLogTerm_ = 0;
  /**
   * <code>int32 lastLogTerm = 4;</code>
   * @return The lastLogTerm.
   */
  @java.lang.Override
  public int getLastLogTerm() {
    return lastLogTerm_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (candidatesTerm_ != 0) {
      output.writeInt32(1, candidatesTerm_);
    }
    if (candidateId_ != 0) {
      output.writeInt32(2, candidateId_);
    }
    if (lastLogIndex_ != 0) {
      output.writeInt32(3, lastLogIndex_);
    }
    if (lastLogTerm_ != 0) {
      output.writeInt32(4, lastLogTerm_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (candidatesTerm_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, candidatesTerm_);
    }
    if (candidateId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, candidateId_);
    }
    if (lastLogIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, lastLogIndex_);
    }
    if (lastLogTerm_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, lastLogTerm_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.ds.paxos.RequestVoteArguments)) {
      return super.equals(obj);
    }
    org.ds.paxos.RequestVoteArguments other = (org.ds.paxos.RequestVoteArguments) obj;

    if (getCandidatesTerm()
        != other.getCandidatesTerm()) return false;
    if (getCandidateId()
        != other.getCandidateId()) return false;
    if (getLastLogIndex()
        != other.getLastLogIndex()) return false;
    if (getLastLogTerm()
        != other.getLastLogTerm()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CANDIDATESTERM_FIELD_NUMBER;
    hash = (53 * hash) + getCandidatesTerm();
    hash = (37 * hash) + CANDIDATEID_FIELD_NUMBER;
    hash = (53 * hash) + getCandidateId();
    hash = (37 * hash) + LASTLOGINDEX_FIELD_NUMBER;
    hash = (53 * hash) + getLastLogIndex();
    hash = (37 * hash) + LASTLOGTERM_FIELD_NUMBER;
    hash = (53 * hash) + getLastLogTerm();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.ds.paxos.RequestVoteArguments parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.RequestVoteArguments parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.RequestVoteArguments parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.RequestVoteArguments parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.RequestVoteArguments parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.RequestVoteArguments parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.RequestVoteArguments parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.ds.paxos.RequestVoteArguments parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.ds.paxos.RequestVoteArguments parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.ds.paxos.RequestVoteArguments parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.ds.paxos.RequestVoteArguments parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.ds.paxos.RequestVoteArguments parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.ds.paxos.RequestVoteArguments prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.ds.paxos.RequestVoteArguments}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.ds.paxos.RequestVoteArguments)
      org.ds.paxos.RequestVoteArgumentsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_RequestVoteArguments_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_RequestVoteArguments_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.ds.paxos.RequestVoteArguments.class, org.ds.paxos.RequestVoteArguments.Builder.class);
    }

    // Construct using org.ds.paxos.RequestVoteArguments.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      candidatesTerm_ = 0;
      candidateId_ = 0;
      lastLogIndex_ = 0;
      lastLogTerm_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_RequestVoteArguments_descriptor;
    }

    @java.lang.Override
    public org.ds.paxos.RequestVoteArguments getDefaultInstanceForType() {
      return org.ds.paxos.RequestVoteArguments.getDefaultInstance();
    }

    @java.lang.Override
    public org.ds.paxos.RequestVoteArguments build() {
      org.ds.paxos.RequestVoteArguments result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.ds.paxos.RequestVoteArguments buildPartial() {
      org.ds.paxos.RequestVoteArguments result = new org.ds.paxos.RequestVoteArguments(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.ds.paxos.RequestVoteArguments result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.candidatesTerm_ = candidatesTerm_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.candidateId_ = candidateId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.lastLogIndex_ = lastLogIndex_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.lastLogTerm_ = lastLogTerm_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.ds.paxos.RequestVoteArguments) {
        return mergeFrom((org.ds.paxos.RequestVoteArguments)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.ds.paxos.RequestVoteArguments other) {
      if (other == org.ds.paxos.RequestVoteArguments.getDefaultInstance()) return this;
      if (other.getCandidatesTerm() != 0) {
        setCandidatesTerm(other.getCandidatesTerm());
      }
      if (other.getCandidateId() != 0) {
        setCandidateId(other.getCandidateId());
      }
      if (other.getLastLogIndex() != 0) {
        setLastLogIndex(other.getLastLogIndex());
      }
      if (other.getLastLogTerm() != 0) {
        setLastLogTerm(other.getLastLogTerm());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              candidatesTerm_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              candidateId_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              lastLogIndex_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              lastLogTerm_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int candidatesTerm_ ;
    /**
     * <code>int32 candidatesTerm = 1;</code>
     * @return The candidatesTerm.
     */
    @java.lang.Override
    public int getCandidatesTerm() {
      return candidatesTerm_;
    }
    /**
     * <code>int32 candidatesTerm = 1;</code>
     * @param value The candidatesTerm to set.
     * @return This builder for chaining.
     */
    public Builder setCandidatesTerm(int value) {

      candidatesTerm_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 candidatesTerm = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCandidatesTerm() {
      bitField0_ = (bitField0_ & ~0x00000001);
      candidatesTerm_ = 0;
      onChanged();
      return this;
    }

    private int candidateId_ ;
    /**
     * <code>int32 candidateId = 2;</code>
     * @return The candidateId.
     */
    @java.lang.Override
    public int getCandidateId() {
      return candidateId_;
    }
    /**
     * <code>int32 candidateId = 2;</code>
     * @param value The candidateId to set.
     * @return This builder for chaining.
     */
    public Builder setCandidateId(int value) {

      candidateId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 candidateId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCandidateId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      candidateId_ = 0;
      onChanged();
      return this;
    }

    private int lastLogIndex_ ;
    /**
     * <code>int32 lastLogIndex = 3;</code>
     * @return The lastLogIndex.
     */
    @java.lang.Override
    public int getLastLogIndex() {
      return lastLogIndex_;
    }
    /**
     * <code>int32 lastLogIndex = 3;</code>
     * @param value The lastLogIndex to set.
     * @return This builder for chaining.
     */
    public Builder setLastLogIndex(int value) {

      lastLogIndex_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 lastLogIndex = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastLogIndex() {
      bitField0_ = (bitField0_ & ~0x00000004);
      lastLogIndex_ = 0;
      onChanged();
      return this;
    }

    private int lastLogTerm_ ;
    /**
     * <code>int32 lastLogTerm = 4;</code>
     * @return The lastLogTerm.
     */
    @java.lang.Override
    public int getLastLogTerm() {
      return lastLogTerm_;
    }
    /**
     * <code>int32 lastLogTerm = 4;</code>
     * @param value The lastLogTerm to set.
     * @return This builder for chaining.
     */
    public Builder setLastLogTerm(int value) {

      lastLogTerm_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 lastLogTerm = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastLogTerm() {
      bitField0_ = (bitField0_ & ~0x00000008);
      lastLogTerm_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:org.ds.paxos.RequestVoteArguments)
  }

  // @@protoc_insertion_point(class_scope:org.ds.paxos.RequestVoteArguments)
  private static final org.ds.paxos.RequestVoteArguments DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.ds.paxos.RequestVoteArguments();
  }

  public static org.ds.paxos.RequestVoteArguments getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RequestVoteArguments>
      PARSER = new com.google.protobuf.AbstractParser<RequestVoteArguments>() {
    @java.lang.Override
    public RequestVoteArguments parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RequestVoteArguments> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RequestVoteArguments> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.ds.paxos.RequestVoteArguments getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

