// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/Raft.proto
// Protobuf Java Version: 4.29.3

package org.ds.paxos;

public interface RequestVoteArgumentsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.ds.paxos.RequestVoteArguments)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 candidatesTerm = 1;</code>
   * @return The candidatesTerm.
   */
  int getCandidatesTerm();

  /**
   * <code>int32 candidateId = 2;</code>
   * @return The candidateId.
   */
  int getCandidateId();

  /**
   * <code>int32 lastLogIndex = 3;</code>
   * @return The lastLogIndex.
   */
  int getLastLogIndex();

  /**
   * <code>int32 lastLogTerm = 4;</code>
   * @return The lastLogTerm.
   */
  int getLastLogTerm();
}
