// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/Raft.proto
// Protobuf Java Version: 4.29.3

package org.ds.paxos;

public interface RequestVoteResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.ds.paxos.RequestVoteResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 currentTerm = 1;</code>
   * @return The currentTerm.
   */
  int getCurrentTerm();

  /**
   * <code>bool isVoteGranted = 2;</code>
   * @return The isVoteGranted.
   */
  boolean getIsVoteGranted();
}
