// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/Raft.proto
// Protobuf Java Version: 4.29.3

package org.ds.paxos;

/**
 * Protobuf type {@code org.ds.paxos.RequestVoteResult}
 */
public final class RequestVoteResult extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:org.ds.paxos.RequestVoteResult)
    RequestVoteResultOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      RequestVoteResult.class.getName());
  }
  // Use RequestVoteResult.newBuilder() to construct.
  private RequestVoteResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RequestVoteResult() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_RequestVoteResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_RequestVoteResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.ds.paxos.RequestVoteResult.class, org.ds.paxos.RequestVoteResult.Builder.class);
  }

  public static final int CURRENTTERM_FIELD_NUMBER = 1;
  private int currentTerm_ = 0;
  /**
   * <code>int32 currentTerm = 1;</code>
   * @return The currentTerm.
   */
  @java.lang.Override
  public int getCurrentTerm() {
    return currentTerm_;
  }

  public static final int ISVOTEGRANTED_FIELD_NUMBER = 2;
  private boolean isVoteGranted_ = false;
  /**
   * <code>bool isVoteGranted = 2;</code>
   * @return The isVoteGranted.
   */
  @java.lang.Override
  public boolean getIsVoteGranted() {
    return isVoteGranted_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (currentTerm_ != 0) {
      output.writeInt32(1, currentTerm_);
    }
    if (isVoteGranted_ != false) {
      output.writeBool(2, isVoteGranted_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (currentTerm_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, currentTerm_);
    }
    if (isVoteGranted_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, isVoteGranted_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.ds.paxos.RequestVoteResult)) {
      return super.equals(obj);
    }
    org.ds.paxos.RequestVoteResult other = (org.ds.paxos.RequestVoteResult) obj;

    if (getCurrentTerm()
        != other.getCurrentTerm()) return false;
    if (getIsVoteGranted()
        != other.getIsVoteGranted()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CURRENTTERM_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentTerm();
    hash = (37 * hash) + ISVOTEGRANTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsVoteGranted());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.ds.paxos.RequestVoteResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.RequestVoteResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.RequestVoteResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.RequestVoteResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.RequestVoteResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.RequestVoteResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.RequestVoteResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.ds.paxos.RequestVoteResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.ds.paxos.RequestVoteResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.ds.paxos.RequestVoteResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.ds.paxos.RequestVoteResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.ds.paxos.RequestVoteResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.ds.paxos.RequestVoteResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.ds.paxos.RequestVoteResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.ds.paxos.RequestVoteResult)
      org.ds.paxos.RequestVoteResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_RequestVoteResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_RequestVoteResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.ds.paxos.RequestVoteResult.class, org.ds.paxos.RequestVoteResult.Builder.class);
    }

    // Construct using org.ds.paxos.RequestVoteResult.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      currentTerm_ = 0;
      isVoteGranted_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_RequestVoteResult_descriptor;
    }

    @java.lang.Override
    public org.ds.paxos.RequestVoteResult getDefaultInstanceForType() {
      return org.ds.paxos.RequestVoteResult.getDefaultInstance();
    }

    @java.lang.Override
    public org.ds.paxos.RequestVoteResult build() {
      org.ds.paxos.RequestVoteResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.ds.paxos.RequestVoteResult buildPartial() {
      org.ds.paxos.RequestVoteResult result = new org.ds.paxos.RequestVoteResult(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.ds.paxos.RequestVoteResult result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.currentTerm_ = currentTerm_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.isVoteGranted_ = isVoteGranted_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.ds.paxos.RequestVoteResult) {
        return mergeFrom((org.ds.paxos.RequestVoteResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.ds.paxos.RequestVoteResult other) {
      if (other == org.ds.paxos.RequestVoteResult.getDefaultInstance()) return this;
      if (other.getCurrentTerm() != 0) {
        setCurrentTerm(other.getCurrentTerm());
      }
      if (other.getIsVoteGranted() != false) {
        setIsVoteGranted(other.getIsVoteGranted());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              currentTerm_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              isVoteGranted_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int currentTerm_ ;
    /**
     * <code>int32 currentTerm = 1;</code>
     * @return The currentTerm.
     */
    @java.lang.Override
    public int getCurrentTerm() {
      return currentTerm_;
    }
    /**
     * <code>int32 currentTerm = 1;</code>
     * @param value The currentTerm to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentTerm(int value) {

      currentTerm_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 currentTerm = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentTerm() {
      bitField0_ = (bitField0_ & ~0x00000001);
      currentTerm_ = 0;
      onChanged();
      return this;
    }

    private boolean isVoteGranted_ ;
    /**
     * <code>bool isVoteGranted = 2;</code>
     * @return The isVoteGranted.
     */
    @java.lang.Override
    public boolean getIsVoteGranted() {
      return isVoteGranted_;
    }
    /**
     * <code>bool isVoteGranted = 2;</code>
     * @param value The isVoteGranted to set.
     * @return This builder for chaining.
     */
    public Builder setIsVoteGranted(boolean value) {

      isVoteGranted_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool isVoteGranted = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsVoteGranted() {
      bitField0_ = (bitField0_ & ~0x00000002);
      isVoteGranted_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:org.ds.paxos.RequestVoteResult)
  }

  // @@protoc_insertion_point(class_scope:org.ds.paxos.RequestVoteResult)
  private static final org.ds.paxos.RequestVoteResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.ds.paxos.RequestVoteResult();
  }

  public static org.ds.paxos.RequestVoteResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RequestVoteResult>
      PARSER = new com.google.protobuf.AbstractParser<RequestVoteResult>() {
    @java.lang.Override
    public RequestVoteResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RequestVoteResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RequestVoteResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.ds.paxos.RequestVoteResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

