// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/Raft.proto
// Protobuf Java Version: 4.29.3

package org.ds.paxos;

public interface TimeStampProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.ds.paxos.TimeStampProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 p = 1;</code>
   * @return The p.
   */
  long getP();

  /**
   * <code>int64 l = 2;</code>
   * @return The l.
   */
  long getL();
}
