// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/Raft.proto
// Protobuf Java Version: 4.29.3

package org.ds.paxos;

/**
 * Protobuf type {@code org.ds.paxos.TokenUpdateRequest}
 */
public final class TokenUpdateRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:org.ds.paxos.TokenUpdateRequest)
    TokenUpdateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      TokenUpdateRequest.class.getName());
  }
  // Use TokenUpdateRequest.newBuilder() to construct.
  private TokenUpdateRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private TokenUpdateRequest() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_TokenUpdateRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_TokenUpdateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.ds.paxos.TokenUpdateRequest.class, org.ds.paxos.TokenUpdateRequest.Builder.class);
  }

  public static final int TOKENSREMAINING_FIELD_NUMBER = 1;
  private double tokensRemaining_ = 0D;
  /**
   * <code>double tokensRemaining = 1;</code>
   * @return The tokensRemaining.
   */
  @java.lang.Override
  public double getTokensRemaining() {
    return tokensRemaining_;
  }

  public static final int LASTUPDATEDTIME_FIELD_NUMBER = 2;
  private long lastUpdatedTime_ = 0L;
  /**
   * <code>int64 lastUpdatedTime = 2;</code>
   * @return The lastUpdatedTime.
   */
  @java.lang.Override
  public long getLastUpdatedTime() {
    return lastUpdatedTime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Double.doubleToRawLongBits(tokensRemaining_) != 0) {
      output.writeDouble(1, tokensRemaining_);
    }
    if (lastUpdatedTime_ != 0L) {
      output.writeInt64(2, lastUpdatedTime_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Double.doubleToRawLongBits(tokensRemaining_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, tokensRemaining_);
    }
    if (lastUpdatedTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, lastUpdatedTime_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.ds.paxos.TokenUpdateRequest)) {
      return super.equals(obj);
    }
    org.ds.paxos.TokenUpdateRequest other = (org.ds.paxos.TokenUpdateRequest) obj;

    if (java.lang.Double.doubleToLongBits(getTokensRemaining())
        != java.lang.Double.doubleToLongBits(
            other.getTokensRemaining())) return false;
    if (getLastUpdatedTime()
        != other.getLastUpdatedTime()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOKENSREMAINING_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTokensRemaining()));
    hash = (37 * hash) + LASTUPDATEDTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastUpdatedTime());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.ds.paxos.TokenUpdateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.TokenUpdateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.TokenUpdateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.TokenUpdateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.TokenUpdateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ds.paxos.TokenUpdateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ds.paxos.TokenUpdateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.ds.paxos.TokenUpdateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.ds.paxos.TokenUpdateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.ds.paxos.TokenUpdateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.ds.paxos.TokenUpdateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.ds.paxos.TokenUpdateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.ds.paxos.TokenUpdateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.ds.paxos.TokenUpdateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.ds.paxos.TokenUpdateRequest)
      org.ds.paxos.TokenUpdateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_TokenUpdateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_TokenUpdateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.ds.paxos.TokenUpdateRequest.class, org.ds.paxos.TokenUpdateRequest.Builder.class);
    }

    // Construct using org.ds.paxos.TokenUpdateRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      tokensRemaining_ = 0D;
      lastUpdatedTime_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.ds.paxos.RaftOuterClass.internal_static_org_ds_paxos_TokenUpdateRequest_descriptor;
    }

    @java.lang.Override
    public org.ds.paxos.TokenUpdateRequest getDefaultInstanceForType() {
      return org.ds.paxos.TokenUpdateRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.ds.paxos.TokenUpdateRequest build() {
      org.ds.paxos.TokenUpdateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.ds.paxos.TokenUpdateRequest buildPartial() {
      org.ds.paxos.TokenUpdateRequest result = new org.ds.paxos.TokenUpdateRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.ds.paxos.TokenUpdateRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.tokensRemaining_ = tokensRemaining_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.lastUpdatedTime_ = lastUpdatedTime_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.ds.paxos.TokenUpdateRequest) {
        return mergeFrom((org.ds.paxos.TokenUpdateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.ds.paxos.TokenUpdateRequest other) {
      if (other == org.ds.paxos.TokenUpdateRequest.getDefaultInstance()) return this;
      if (other.getTokensRemaining() != 0D) {
        setTokensRemaining(other.getTokensRemaining());
      }
      if (other.getLastUpdatedTime() != 0L) {
        setLastUpdatedTime(other.getLastUpdatedTime());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              tokensRemaining_ = input.readDouble();
              bitField0_ |= 0x00000001;
              break;
            } // case 9
            case 16: {
              lastUpdatedTime_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private double tokensRemaining_ ;
    /**
     * <code>double tokensRemaining = 1;</code>
     * @return The tokensRemaining.
     */
    @java.lang.Override
    public double getTokensRemaining() {
      return tokensRemaining_;
    }
    /**
     * <code>double tokensRemaining = 1;</code>
     * @param value The tokensRemaining to set.
     * @return This builder for chaining.
     */
    public Builder setTokensRemaining(double value) {

      tokensRemaining_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>double tokensRemaining = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTokensRemaining() {
      bitField0_ = (bitField0_ & ~0x00000001);
      tokensRemaining_ = 0D;
      onChanged();
      return this;
    }

    private long lastUpdatedTime_ ;
    /**
     * <code>int64 lastUpdatedTime = 2;</code>
     * @return The lastUpdatedTime.
     */
    @java.lang.Override
    public long getLastUpdatedTime() {
      return lastUpdatedTime_;
    }
    /**
     * <code>int64 lastUpdatedTime = 2;</code>
     * @param value The lastUpdatedTime to set.
     * @return This builder for chaining.
     */
    public Builder setLastUpdatedTime(long value) {

      lastUpdatedTime_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 lastUpdatedTime = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastUpdatedTime() {
      bitField0_ = (bitField0_ & ~0x00000002);
      lastUpdatedTime_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:org.ds.paxos.TokenUpdateRequest)
  }

  // @@protoc_insertion_point(class_scope:org.ds.paxos.TokenUpdateRequest)
  private static final org.ds.paxos.TokenUpdateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.ds.paxos.TokenUpdateRequest();
  }

  public static org.ds.paxos.TokenUpdateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TokenUpdateRequest>
      PARSER = new com.google.protobuf.AbstractParser<TokenUpdateRequest>() {
    @java.lang.Override
    public TokenUpdateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TokenUpdateRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TokenUpdateRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.ds.paxos.TokenUpdateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

