// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/Raft.proto
// Protobuf Java Version: 4.29.3

package org.ds.paxos;

public interface TokenStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.ds.paxos.TokenStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double tokensAvailable = 1;</code>
   * @return The tokensAvailable.
   */
  double getTokensAvailable();

  /**
   * <code>int64 lastUpdatedTime = 2;</code>
   * @return The lastUpdatedTime.
   */
  long getLastUpdatedTime();
}
