// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/Raft.proto
// Protobuf Java Version: 4.29.3

package org.ds.paxos;

public interface TokenConsumeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.ds.paxos.TokenConsumeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double requiredTokens = 1;</code>
   * @return The requiredTokens.
   */
  double getRequiredTokens();
}
