// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/Raft.proto
// Protobuf Java Version: 4.29.3

package org.ds.paxos;

public interface TokenStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.ds.paxos.TokenStatusRequest)
    com.google.protobuf.MessageOrBuilder {
}
