// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/Raft.proto
// Protobuf Java Version: 4.29.3

package org.ds.paxos;

public interface TokenConsumeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.ds.paxos.TokenConsumeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool granted = 1;</code>
   * @return The granted.
   */
  boolean getGranted();

  /**
   * <code>double tokensRemaining = 2;</code>
   * @return The tokensRemaining.
   */
  double getTokensRemaining();

  /**
   * <code>int64 lastUpdatedTime = 3;</code>
   * @return The lastUpdatedTime.
   */
  long getLastUpdatedTime();
}
