// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/Raft.proto
// Protobuf Java Version: 4.29.3

package org.ds.paxos;

public interface TransactionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.ds.paxos.Transaction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sender = 1;</code>
   * @return The sender.
   */
  java.lang.String getSender();
  /**
   * <code>string sender = 1;</code>
   * @return The bytes for sender.
   */
  com.google.protobuf.ByteString
      getSenderBytes();

  /**
   * <code>string receiver = 2;</code>
   * @return The receiver.
   */
  java.lang.String getReceiver();
  /**
   * <code>string receiver = 2;</code>
   * @return The bytes for receiver.
   */
  com.google.protobuf.ByteString
      getReceiverBytes();

  /**
   * <code>double amount = 3;</code>
   * @return The amount.
   */
  double getAmount();

  /**
   * <code>string id = 4;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 4;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
